// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuditLog = "audit_logs"

// AuditLog mapped from table <audit_logs>
type AuditLog struct {
	ID             string    `gorm:"column:id;primaryKey;comment:日志ID (UUID)" json:"id"`                                               // 日志ID (UUID)
	UserID         string    `gorm:"column:user_id;comment:操作用户ID" json:"user_id"`                                                     // 操作用户ID
	Username       string    `gorm:"column:username;comment:用户名" json:"username"`                                                      // 用户名
	OrganizationID string    `gorm:"column:organization_id;comment:所属组织ID" json:"organization_id"`                                     // 所属组织ID
	Module         string    `gorm:"column:module;not null;comment:模块名称: login, certificate, verification, system, api" json:"module"` // 模块名称: login, certificate, verification, system, api
	Action         string    `gorm:"column:action;not null;comment:操作类型" json:"action"`                                                // 操作类型
	ResourceType   string    `gorm:"column:resource_type;comment:资源类型" json:"resource_type"`                                           // 资源类型
	ResourceID     string    `gorm:"column:resource_id;comment:资源ID" json:"resource_id"`                                               // 资源ID
	ResourceName   string    `gorm:"column:resource_name;comment:资源名称" json:"resource_name"`                                           // 资源名称
	Description    string    `gorm:"column:description;comment:操作描述" json:"description"`                                               // 操作描述
	RequestData    string    `gorm:"column:request_data;comment:请求数据" json:"request_data"`                                             // 请求数据
	ResponseData   string    `gorm:"column:response_data;comment:响应数据" json:"response_data"`                                           // 响应数据
	IPAddress      string    `gorm:"column:ip_address;comment:IP地址" json:"ip_address"`                                                 // IP地址
	UserAgent      string    `gorm:"column:user_agent;comment:User-Agent" json:"user_agent"`                                           // User-Agent
	Location       string    `gorm:"column:location;comment:地理位置" json:"location"`                                                     // 地理位置
	DeviceInfo     string    `gorm:"column:device_info;comment:设备信息" json:"device_info"`                                               // 设备信息
	LoginSuccess   bool      `gorm:"column:login_success;default:1;comment:是否成功" json:"login_success"`                                 // 是否成功
	ErrorMessage   string    `gorm:"column:error_message;comment:错误信息" json:"error_message"`                                           // 错误信息
	TraceID        string    `gorm:"column:trace_id;comment:链路追踪ID" json:"trace_id"`                                                   // 链路追踪ID
	DurationMs     int64     `gorm:"column:duration_ms;comment:耗时 (毫秒)" json:"duration_ms"`                                            // 耗时 (毫秒)
	CreatedAt      time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                 // 创建时间
}

// TableName AuditLog's table name
func (*AuditLog) TableName() string {
	return TableNameAuditLog
}
