// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlockchainNetwork = "blockchain_networks"

// BlockchainNetwork mapped from table <blockchain_networks>
type BlockchainNetwork struct {
	ID          string    `gorm:"column:id;primaryKey;comment:网络ID (UUID)" json:"id"`                          // 网络ID (UUID)
	Name        string    `gorm:"column:name;not null;comment:网络名称" json:"name"`                               // 网络名称
	Code        string    `gorm:"column:code;not null;comment:网络代码 (唯一标识)" json:"code"`                        // 网络代码 (唯一标识)
	Type        int32     `gorm:"column:type;default:1;comment:区块链类型: 1-Fabric, 2-Ethereum" json:"type"`       // 区块链类型: 1-Fabric, 2-Ethereum
	ChainID     int64     `gorm:"column:chain_id;comment:链ID" json:"chain_id"`                                 // 链ID
	EndpointURL string    `gorm:"column:endpoint_url;not null;comment:节点RPC endpoint URL" json:"endpoint_url"` // 节点RPC endpoint URL
	ExplorerURL string    `gorm:"column:explorer_url;comment:区块链浏览器URL" json:"explorer_url"`                   // 区块链浏览器URL
	Status      int32     `gorm:"column:status;default:1;comment:状态: 1-正常, 2-维护中, 3-停用" json:"status"`         // 状态: 1-正常, 2-维护中, 3-停用
	IsDefault   bool      `gorm:"column:is_default;comment:是否默认网络" json:"is_default"`                          // 是否默认网络
	ExtraData   string    `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`                            // 扩展数据
	CreatedAt   time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                            // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                            // 更新时间
}

// TableName BlockchainNetwork's table name
func (*BlockchainNetwork) TableName() string {
	return TableNameBlockchainNetwork
}
