// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlockchainTransaction = "blockchain_transactions"

// BlockchainTransaction mapped from table <blockchain_transactions>
type BlockchainTransaction struct {
	ID             string    `gorm:"column:id;primaryKey;comment:交易ID (UUID)" json:"id"`                                 // 交易ID (UUID)
	TxHash         string    `gorm:"column:tx_hash;not null;comment:交易哈希 (唯一)" json:"tx_hash"`                           // 交易哈希 (唯一)
	NetworkID      string    `gorm:"column:network_id;not null;comment:区块链网络ID" json:"network_id"`                       // 区块链网络ID
	CertificateID  string    `gorm:"column:certificate_id;comment:关联证书ID" json:"certificate_id"`                         // 关联证书ID
	TxType         int32     `gorm:"column:tx_type;default:1;comment:交易类型: 1-存证, 2-撤销, 3-查询, 4-转让" json:"tx_type"`       // 交易类型: 1-存证, 2-撤销, 3-查询, 4-转让
	FromAddress    string    `gorm:"column:from_address;comment:发起方地址" json:"from_address"`                              // 发起方地址
	ToAddress      string    `gorm:"column:to_address;comment:接收方地址" json:"to_address"`                                  // 接收方地址
	Data           string    `gorm:"column:data;comment:交易数据" json:"data"`                                               // 交易数据
	Value          float64   `gorm:"column:value;comment:交易金额" json:"value"`                                             // 交易金额
	GasUsed        int64     `gorm:"column:gas_used;comment:Gas消耗" json:"gas_used"`                                      // Gas消耗
	TxFee          float64   `gorm:"column:tx_fee;comment:交易手续费" json:"tx_fee"`                                          // 交易手续费
	BlockNumber    int64     `gorm:"column:block_number;comment:区块高度" json:"block_number"`                               // 区块高度
	BlockHash      string    `gorm:"column:block_hash;comment:区块哈希" json:"block_hash"`                                   // 区块哈希
	BlockTimestamp time.Time `gorm:"column:block_timestamp;comment:区块时间戳" json:"block_timestamp"`                        // 区块时间戳
	Confirmations  int64     `gorm:"column:confirmations;comment:确认数" json:"confirmations"`                              // 确认数
	Status         int32     `gorm:"column:status;default:1;comment:交易状态: 1-待处理, 2-处理中, 3-成功, 4-失败, 5-超时" json:"status"` // 交易状态: 1-待处理, 2-处理中, 3-成功, 4-失败, 5-超时
	ErrorMessage   string    `gorm:"column:error_message;comment:错误信息" json:"error_message"`                             // 错误信息
	CertHash       string    `gorm:"column:cert_hash;comment:证书数据哈希" json:"cert_hash"`                                   // 证书数据哈希
	OwnerAddress   string    `gorm:"column:owner_address;comment:所有者区块链地址" json:"owner_address"`                         // 所有者区块链地址
	TokenID        string    `gorm:"column:token_id;comment:NFT Token ID" json:"token_id"`                               // NFT Token ID
	URI            string    `gorm:"column:uri;comment:元数据URI" json:"uri"`                                               // 元数据URI
	CreatedAt      time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                   // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                   // 更新时间
}

// TableName BlockchainTransaction's table name
func (*BlockchainTransaction) TableName() string {
	return TableNameBlockchainTransaction
}
