// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCertificateType = "certificate_types"

// CertificateType mapped from table <certificate_types>
type CertificateType struct {
	ID          string    `gorm:"column:id;primaryKey;comment:类型ID (UUID)" json:"id"`                                          // 类型ID (UUID)
	Code        string    `gorm:"column:code;not null;comment:类型代码 (唯一标识)" json:"code"`                                        // 类型代码 (唯一标识)
	Name        string    `gorm:"column:name;not null;comment:类型名称" json:"name"`                                               // 类型名称
	Category    int32     `gorm:"column:category;default:1;comment:证书类别: 1-毕业证书, 2-学位证书, 3-成绩单, 4-资格证书, 5-其他" json:"category"` // 证书类别: 1-毕业证书, 2-学位证书, 3-成绩单, 4-资格证书, 5-其他
	DegreeLevel int32     `gorm:"column:degree_level;comment:学位等级: 1-学士, 2-硕士, 3-博士" json:"degree_level"`                      // 学位等级: 1-学士, 2-硕士, 3-博士
	Description string    `gorm:"column:description;comment:类型描述" json:"description"`                                          // 类型描述
	IsActive    bool      `gorm:"column:is_active;default:1;comment:是否启用" json:"is_active"`                                    // 是否启用
	SortOrder   int64     `gorm:"column:sort_order;comment:排序序号" json:"sort_order"`                                            // 排序序号
	ExtraData   string    `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`                                            // 扩展数据
	CreatedAt   time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                            // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                            // 更新时间
}

// TableName CertificateType's table name
func (*CertificateType) TableName() string {
	return TableNameCertificateType
}
