// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCertificateBatch = "certificate_batches"

// CertificateBatch mapped from table <certificate_batches>
type CertificateBatch struct {
	ID             string    `gorm:"column:id;primaryKey;comment:批次ID (UUID)" json:"id"`                                    // 批次ID (UUID)
	BatchNo        string    `gorm:"column:batch_no;not null;comment:批次号 (唯一)" json:"batch_no"`                             // 批次号 (唯一)
	TypeID         string    `gorm:"column:type_id;not null;comment:证书类型ID" json:"type_id"`                                 // 证书类型ID
	OrganizationID string    `gorm:"column:organization_id;not null;comment:发证机构ID" json:"organization_id"`                 // 发证机构ID
	TemplateID     string    `gorm:"column:template_id;comment:模板ID" json:"template_id"`                                    // 模板ID
	Name           string    `gorm:"column:name;not null;comment:批次名称" json:"name"`                                         // 批次名称
	Description    string    `gorm:"column:description;comment:批次描述" json:"description"`                                    // 批次描述
	TotalCount     int64     `gorm:"column:total_count;comment:总数量" json:"total_count"`                                     // 总数量
	SuccessCount   int64     `gorm:"column:success_count;comment:成功数量" json:"success_count"`                                // 成功数量
	FailCount      int64     `gorm:"column:fail_count;comment:失败数量" json:"fail_count"`                                      // 失败数量
	Status         int32     `gorm:"column:status;default:1;comment:批次状态: 1-待处理, 2-处理中, 3-已完成, 4-已暂停, 5-已取消" json:"status"` // 批次状态: 1-待处理, 2-处理中, 3-已完成, 4-已暂停, 5-已取消
	ImportFileURL  string    `gorm:"column:import_file_url;comment:导入文件URL" json:"import_file_url"`                         // 导入文件URL
	ExecutedBy     string    `gorm:"column:executed_by;comment:执行人ID" json:"executed_by"`                                   // 执行人ID
	StartedAt      time.Time `gorm:"column:started_at;comment:开始时间" json:"started_at"`                                      // 开始时间
	CompletedAt    time.Time `gorm:"column:completed_at;comment:完成时间" json:"completed_at"`                                  // 完成时间
	CreatedAt      time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                      // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                      // 更新时间
}

// TableName CertificateBatch's table name
func (*CertificateBatch) TableName() string {
	return TableNameCertificateBatch
}
