// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCertificate = "certificates"

// Certificate mapped from table <certificates>
type Certificate struct {
	ID                  string         `gorm:"column:id;primaryKey;comment:证书ID (UUID)" json:"id"`                                                // 证书ID (UUID)
	CertificateNo       string         `gorm:"column:certificate_no;not null;comment:证书编号 (唯一)" json:"certificate_no"`                            // 证书编号 (唯一)
	TypeID              string         `gorm:"column:type_id;not null;comment:证书类型ID" json:"type_id"`                                             // 证书类型ID
	UserID              string         `gorm:"column:user_id;not null;comment:持有人用户ID" json:"user_id"`                                            // 持有人用户ID
	OrganizationID      string         `gorm:"column:organization_id;not null;comment:发证机构ID" json:"organization_id"`                             // 发证机构ID
	TemplateID          string         `gorm:"column:template_id;comment:使用的模板ID" json:"template_id"`                                             // 使用的模板ID
	StudentNo           string         `gorm:"column:student_no;comment:学号" json:"student_no"`                                                    // 学号
	Name                string         `gorm:"column:name;not null;comment:证书持有人姓名" json:"name"`                                                  // 证书持有人姓名
	IDCardNumber        string         `gorm:"column:id_card_number;comment:身份证号" json:"id_card_number"`                                          // 身份证号
	Gender              int32          `gorm:"column:gender;comment:性别: 1-男, 2-女" json:"gender"`                                                  // 性别: 1-男, 2-女
	Major               string         `gorm:"column:major;comment:专业名称" json:"major"`                                                            // 专业名称
	MajorCode           string         `gorm:"column:major_code;comment:专业代码" json:"major_code"`                                                  // 专业代码
	Degree              int32          `gorm:"column:degree;default:1;comment:学位等级: 1-学士, 2-硕士, 3-博士, 4-无学位, 5-专科" json:"degree"`                 // 学位等级: 1-学士, 2-硕士, 3-博士, 4-无学位, 5-专科
	DegreeName          string         `gorm:"column:degree_name;comment:学位名称" json:"degree_name"`                                                // 学位名称
	EducationLevel      int32          `gorm:"column:education_level;comment:学历层次" json:"education_level"`                                        // 学历层次
	EducationType       int32          `gorm:"column:education_type;default:1;comment:办学类型: 1-全日制, 2-非全日制, 3-成人教育" json:"education_type"`         // 办学类型: 1-全日制, 2-非全日制, 3-成人教育
	EnrollmentDate      time.Time      `gorm:"column:enrollment_date;comment:入学日期" json:"enrollment_date"`                                        // 入学日期
	GraduationDate      time.Time      `gorm:"column:graduation_date;comment:毕业日期" json:"graduation_date"`                                        // 毕业日期
	StudyPeriod         string         `gorm:"column:study_period;comment:学习期限" json:"study_period"`                                              // 学习期限
	SchoolSystem        string         `gorm:"column:school_system;comment:学制" json:"school_system"`                                              // 学制
	Campus              string         `gorm:"column:campus;comment:校区" json:"campus"`                                                            // 校区
	Gpa                 float64        `gorm:"column:gpa;comment:平均学分绩点" json:"gpa"`                                                              // 平均学分绩点
	TotalCredits        float64        `gorm:"column:total_credits;comment:总学分" json:"total_credits"`                                             // 总学分
	Status              int32          `gorm:"column:status;default:1;comment:证书状态: 1-有效, 2-已撤销, 3-已挂失, 4-草稿, 5-审核中" json:"status"`               // 证书状态: 1-有效, 2-已撤销, 3-已挂失, 4-草稿, 5-审核中
	IssueDate           time.Time      `gorm:"column:issue_date;comment:发证日期" json:"issue_date"`                                                  // 发证日期
	ValidFromDate       time.Time      `gorm:"column:valid_from_date;comment:有效开始日期" json:"valid_from_date"`                                      // 有效开始日期
	ValidUntilDate      time.Time      `gorm:"column:valid_until_date;comment:有效结束日期" json:"valid_until_date"`                                    // 有效结束日期
	BlockchainTxHash    string         `gorm:"column:blockchain_tx_hash;comment:区块链交易哈希" json:"blockchain_tx_hash"`                               // 区块链交易哈希
	BlockchainCertHash  string         `gorm:"column:blockchain_cert_hash;comment:证书数据哈希" json:"blockchain_cert_hash"`                            // 证书数据哈希
	BlockchainBlockNo   int64          `gorm:"column:blockchain_block_no;comment:区块链块号" json:"blockchain_block_no"`                               // 区块链块号
	BlockchainTimestamp time.Time      `gorm:"column:blockchain_timestamp;comment:区块链时间戳" json:"blockchain_timestamp"`                            // 区块链时间戳
	OnChainStatus       int32          `gorm:"column:on_chain_status;default:1;comment:上链状态: 1-待上链, 2-上链中, 3-已上链, 4-上链失败" json:"on_chain_status"` // 上链状态: 1-待上链, 2-上链中, 3-已上链, 4-上链失败
	OnChainAt           time.Time      `gorm:"column:on_chain_at;comment:上链时间" json:"on_chain_at"`                                                // 上链时间
	PdfURL              string         `gorm:"column:pdf_url;comment:PDF文件URL" json:"pdf_url"`                                                    // PDF文件URL
	PdfHash             string         `gorm:"column:pdf_hash;comment:PDF文件哈希" json:"pdf_hash"`                                                   // PDF文件哈希
	PdfSignedBy         string         `gorm:"column:pdf_signed_by;comment:PDF签名人ID" json:"pdf_signed_by"`                                        // PDF签名人ID
	PdfSignedAt         time.Time      `gorm:"column:pdf_signed_at;comment:PDF签名时间" json:"pdf_signed_at"`                                         // PDF签名时间
	SignedBy            string         `gorm:"column:signed_by;comment:证书签发人ID" json:"signed_by"`                                                 // 证书签发人ID
	IssuedBy            string         `gorm:"column:issued_by;comment:操作人ID" json:"issued_by"`                                                   // 操作人ID
	IssueReason         string         `gorm:"column:issue_reason;comment:颁发原因" json:"issue_reason"`                                              // 颁发原因
	RevokedAt           time.Time      `gorm:"column:revoked_at;comment:撤销时间" json:"revoked_at"`                                                  // 撤销时间
	RevokedBy           string         `gorm:"column:revoked_by;comment:撤销人ID" json:"revoked_by"`                                                 // 撤销人ID
	RevokeReason        string         `gorm:"column:revoke_reason;comment:撤销原因" json:"revoke_reason"`                                            // 撤销原因
	VerificationCount   int64          `gorm:"column:verification_count;comment:验证次数" json:"verification_count"`                                  // 验证次数
	LastVerifiedAt      time.Time      `gorm:"column:last_verified_at;comment:最后验证时间" json:"last_verified_at"`                                    // 最后验证时间
	ExtraData           string         `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`                                                  // 扩展数据
	CreatedAt           time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                  // 创建时间
	UpdatedAt           time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                                  // 更新时间
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                                  // 删除时间
	Version             int64          `gorm:"column:version;default:1;comment:版本号" json:"version"`                                               // 版本号
}

// TableName Certificate's table name
func (*Certificate) TableName() string {
	return TableNameCertificate
}
