// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCertificateTemplate = "certificate_templates"

// CertificateTemplate mapped from table <certificate_templates>
type CertificateTemplate struct {
	ID              string    `gorm:"column:id;primaryKey;comment:模板ID (UUID)" json:"id"`                // 模板ID (UUID)
	Name            string    `gorm:"column:name;not null;comment:模板名称" json:"name"`                     // 模板名称
	Code            string    `gorm:"column:code;not null;comment:模板代码 (唯一标识)" json:"code"`              // 模板代码 (唯一标识)
	TypeID          string    `gorm:"column:type_id;not null;comment:证书类型ID" json:"type_id"`             // 证书类型ID
	ThumbnailURL    string    `gorm:"column:thumbnail_url;comment:缩略图URL" json:"thumbnail_url"`          // 缩略图URL
	TemplateFileURL string    `gorm:"column:template_file_url;comment:模板文件URL" json:"template_file_url"` // 模板文件URL
	TemplateData    string    `gorm:"column:template_data;comment:模板配置数据" json:"template_data"`          // 模板配置数据
	Fields          string    `gorm:"column:fields;not null;comment:模板字段配置" json:"fields"`               // 模板字段配置
	IsDefault       bool      `gorm:"column:is_default;comment:是否默认模板" json:"is_default"`                // 是否默认模板
	IsActive        bool      `gorm:"column:is_active;default:1;comment:是否启用" json:"is_active"`          // 是否启用
	Version         int64     `gorm:"column:version;default:1;comment:版本号" json:"version"`               // 版本号
	OrganizationID  string    `gorm:"column:organization_id;comment:所属组织ID" json:"organization_id"`      // 所属组织ID
	CreatedBy       string    `gorm:"column:created_by;comment:创建人ID" json:"created_by"`                 // 创建人ID
	CreatedAt       time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                  // 更新时间
}

// TableName CertificateTemplate's table name
func (*CertificateTemplate) TableName() string {
	return TableNameCertificateTemplate
}
