// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDepartment = "departments"

// Department mapped from table <departments>
type Department struct {
	ID             string         `gorm:"column:id;primaryKey;comment:部门ID (UUID)" json:"id"`                           // 部门ID (UUID)
	OrganizationID string         `gorm:"column:organization_id;not null;comment:所属组织ID" json:"organization_id"`        // 所属组织ID
	ParentID       string         `gorm:"column:parent_id;comment:上级部门ID" json:"parent_id"`                             // 上级部门ID
	Name           string         `gorm:"column:name;not null;comment:部门名称" json:"name"`                                // 部门名称
	Code           string         `gorm:"column:code;comment:部门代码" json:"code"`                                         // 部门代码
	Type           int32          `gorm:"column:type;default:1;comment:部门类型: 1-职能部门, 2-教学部门, 3-行政部门, 4-其他" json:"type"` // 部门类型: 1-职能部门, 2-教学部门, 3-行政部门, 4-其他
	Description    string         `gorm:"column:description;comment:部门描述" json:"description"`                           // 部门描述
	LeaderID       string         `gorm:"column:leader_id;comment:负责人ID" json:"leader_id"`                              // 负责人ID
	SortOrder      int64          `gorm:"column:sort_order;comment:排序序号" json:"sort_order"`                             // 排序序号
	IsActive       bool           `gorm:"column:is_active;default:1;comment:是否启用" json:"is_active"`                     // 是否启用
	Level          int64          `gorm:"column:level;default:1;comment:部门层级" json:"level"`                             // 部门层级
	Path           string         `gorm:"column:path;comment:部门路径" json:"path"`                                         // 部门路径
	ExtraData      string         `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`                             // 扩展数据
	CreatedAt      time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                             // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                             // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                             // 删除时间
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
