// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDictionary = "dictionaries"

// Dictionary mapped from table <dictionaries>
type Dictionary struct {
	ID          string    `gorm:"column:id;primaryKey;comment:字典ID (UUID)" json:"id"`        // 字典ID (UUID)
	TypeCode    string    `gorm:"column:type_code;not null;comment:字典类型代码" json:"type_code"` // 字典类型代码
	Code        string    `gorm:"column:code;not null;comment:字典项代码" json:"code"`            // 字典项代码
	Name        string    `gorm:"column:name;not null;comment:字典项名称" json:"name"`            // 字典项名称
	Value       string    `gorm:"column:value;comment:字典项值" json:"value"`                    // 字典项值
	ParentCode  string    `gorm:"column:parent_code;comment:父级代码" json:"parent_code"`        // 父级代码
	Description string    `gorm:"column:description;comment:描述" json:"description"`          // 描述
	SortOrder   int64     `gorm:"column:sort_order;comment:排序序号" json:"sort_order"`          // 排序序号
	IsActive    bool      `gorm:"column:is_active;default:1;comment:是否启用" json:"is_active"`  // 是否启用
	ExtraData   string    `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`          // 扩展数据
	CreatedAt   time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`          // 更新时间
}

// TableName Dictionary's table name
func (*Dictionary) TableName() string {
	return TableNameDictionary
}
