// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFileRecord = "file_records"

// FileRecord mapped from table <file_records>
type FileRecord struct {
	ID             string    `gorm:"column:id;primaryKey;comment:文件ID (UUID)" json:"id"`                                         // 文件ID (UUID)
	FileName       string    `gorm:"column:file_name;not null;comment:文件名" json:"file_name"`                                     // 文件名
	FilePath       string    `gorm:"column:file_path;not null;comment:文件路径" json:"file_path"`                                    // 文件路径
	FileURL        string    `gorm:"column:file_url;not null;comment:文件访问URL" json:"file_url"`                                   // 文件访问URL
	FileType       string    `gorm:"column:file_type;not null;comment:文件类型: pdf, image, excel, word, zip" json:"file_type"`      // 文件类型: pdf, image, excel, word, zip
	MimeType       string    `gorm:"column:mime_type;comment:MIME类型" json:"mime_type"`                                           // MIME类型
	FileSize       int64     `gorm:"column:file_size;not null;comment:文件大小 (字节)" json:"file_size"`                               // 文件大小 (字节)
	FileHash       string    `gorm:"column:file_hash;comment:文件哈希值 (SHA256)" json:"file_hash"`                                   // 文件哈希值 (SHA256)
	StorageType    int32     `gorm:"column:storage_type;default:1;comment:存储类型: 1-本地, 2-OSS, 3-S3, 4-MinIO" json:"storage_type"` // 存储类型: 1-本地, 2-OSS, 3-S3, 4-MinIO
	StorageBucket  string    `gorm:"column:storage_bucket;comment:存储桶名称" json:"storage_bucket"`                                  // 存储桶名称
	StorageKey     string    `gorm:"column:storage_key;comment:存储键" json:"storage_key"`                                          // 存储键
	UploadedBy     string    `gorm:"column:uploaded_by;comment:上传人ID" json:"uploaded_by"`                                        // 上传人ID
	OrganizationID string    `gorm:"column:organization_id;comment:组织ID" json:"organization_id"`                                 // 组织ID
	RelatedType    string    `gorm:"column:related_type;comment:关联业务类型" json:"related_type"`                                     // 关联业务类型
	RelatedID      string    `gorm:"column:related_id;comment:关联业务ID" json:"related_id"`                                         // 关联业务ID
	Description    string    `gorm:"column:description;comment:文件描述" json:"description"`                                         // 文件描述
	IsActive       bool      `gorm:"column:is_active;default:1;comment:是否有效" json:"is_active"`                                   // 是否有效
	IsTemp         bool      `gorm:"column:is_temp;comment:是否临时文件" json:"is_temp"`                                               // 是否临时文件
	ExpiresAt      time.Time `gorm:"column:expires_at;comment:过期时间" json:"expires_at"`                                           // 过期时间
	AccessCount    int64     `gorm:"column:access_count;comment:访问次数" json:"access_count"`                                       // 访问次数
	CreatedAt      time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                           // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                           // 更新时间
}

// TableName FileRecord's table name
func (*FileRecord) TableName() string {
	return TableNameFileRecord
}
