// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganizationUser = "organization_users"

// OrganizationUser mapped from table <organization_users>
type OrganizationUser struct {
	ID              string    `gorm:"column:id;primaryKey;comment:记录ID (UUID)" json:"id"`                                           // 记录ID (UUID)
	OrganizationID  string    `gorm:"column:organization_id;not null;comment:组织ID" json:"organization_id"`                          // 组织ID
	UserID          string    `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                          // 用户ID
	DepartmentID    string    `gorm:"column:department_id;comment:部门ID" json:"department_id"`                                       // 部门ID
	DepartmentName  string    `gorm:"column:department_name;comment:部门名称" json:"department_name"`                                   // 部门名称
	Position        string    `gorm:"column:position;comment:职位" json:"position"`                                                   // 职位
	PositionTitle   string    `gorm:"column:position_title;comment:职称" json:"position_title"`                                       // 职称
	EmployeeID      string    `gorm:"column:employee_id;comment:员工号" json:"employee_id"`                                            // 员工号
	HireDate        time.Time `gorm:"column:hire_date;comment:入职日期" json:"hire_date"`                                               // 入职日期
	ResignationDate time.Time `gorm:"column:resignation_date;comment:离职日期" json:"resignation_date"`                                 // 离职日期
	EmploymentType  int32     `gorm:"column:employment_type;default:1;comment:用工类型: 1-正式, 2-合同, 3-实习, 4-外包" json:"employment_type"` // 用工类型: 1-正式, 2-合同, 3-实习, 4-外包
	WorkStatus      int32     `gorm:"column:work_status;default:1;comment:工作状态: 1-在职, 2-离职, 3-退休, 4-停薪留职" json:"work_status"`       // 工作状态: 1-在职, 2-离职, 3-退休, 4-停薪留职
	IsPrimary       bool      `gorm:"column:is_primary;comment:是否为主组织" json:"is_primary"`                                           // 是否为主组织
	IsAdmin         bool      `gorm:"column:is_admin;comment:是否管理员" json:"is_admin"`                                                // 是否管理员
	JoinedAt        time.Time `gorm:"column:joined_at;comment:加入时间" json:"joined_at"`                                               // 加入时间
	LeftAt          time.Time `gorm:"column:left_at;comment:离开时间" json:"left_at"`                                                   // 离开时间
	CreatedAt       time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                             // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                             // 更新时间
}

// TableName OrganizationUser's table name
func (*OrganizationUser) TableName() string {
	return TableNameOrganizationUser
}
