// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrganization = "organizations"

// Organization mapped from table <organizations>
type Organization struct {
	ID              string         `gorm:"column:id;primaryKey;comment:组织ID (UUID)" json:"id"`                               // 组织ID (UUID)
	Name            string         `gorm:"column:name;not null;comment:组织名称" json:"name"`                                    // 组织名称
	Code            string         `gorm:"column:code;not null;comment:组织代码 (唯一标识)" json:"code"`                             // 组织代码 (唯一标识)
	Type            int32          `gorm:"column:type;default:5;comment:组织类型: 1-监管机构, 2-高校, 3-企业, 4-政府机构, 5-其他" json:"type"` // 组织类型: 1-监管机构, 2-高校, 3-企业, 4-政府机构, 5-其他
	ShortName       string         `gorm:"column:short_name;comment:组织简称" json:"short_name"`                                 // 组织简称
	LogoURL         string         `gorm:"column:logo_url;comment:Logo URL" json:"logo_url"`                                 // Logo URL
	Description     string         `gorm:"column:description;comment:组织描述" json:"description"`                               // 组织描述
	Address         string         `gorm:"column:address;comment:地址" json:"address"`                                         // 地址
	Province        string         `gorm:"column:province;comment:省份" json:"province"`                                       // 省份
	City            string         `gorm:"column:city;comment:城市" json:"city"`                                               // 城市
	District        string         `gorm:"column:district;comment:区县" json:"district"`                                       // 区县
	PostalCode      string         `gorm:"column:postal_code;comment:邮政编码" json:"postal_code"`                               // 邮政编码
	Website         string         `gorm:"column:website;comment:官方网站" json:"website"`                                       // 官方网站
	Email           string         `gorm:"column:email;comment:联系邮箱" json:"email"`                                           // 联系邮箱
	Phone           string         `gorm:"column:phone;comment:联系电话" json:"phone"`                                           // 联系电话
	ContactName     string         `gorm:"column:contact_name;comment:联系人姓名" json:"contact_name"`                            // 联系人姓名
	ContactPhone    string         `gorm:"column:contact_phone;comment:联系人电话" json:"contact_phone"`                          // 联系人电话
	ContactEmail    string         `gorm:"column:contact_email;comment:联系人邮箱" json:"contact_email"`                          // 联系人邮箱
	Industry        string         `gorm:"column:industry;comment:所属行业" json:"industry"`                                     // 所属行业
	Scale           string         `gorm:"column:scale;comment:组织规模" json:"scale"`                                           // 组织规模
	EstablishedDate time.Time      `gorm:"column:established_date;comment:成立日期" json:"established_date"`                     // 成立日期
	IsActive        bool           `gorm:"column:is_active;default:1;comment:是否启用" json:"is_active"`                         // 是否启用
	IsVerified      bool           `gorm:"column:is_verified;comment:是否已认证" json:"is_verified"`                              // 是否已认证
	VerifiedAt      time.Time      `gorm:"column:verified_at;comment:认证时间" json:"verified_at"`                               // 认证时间
	ParentID        string         `gorm:"column:parent_id;comment:上级组织ID" json:"parent_id"`                                 // 上级组织ID
	Level           int64          `gorm:"column:level;default:1;comment:组织层级" json:"level"`                                 // 组织层级
	SortOrder       int64          `gorm:"column:sort_order;comment:排序序号" json:"sort_order"`                                 // 排序序号
	ExtraData       string         `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`                                 // 扩展数据
	CreatedAt       time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                 // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                 // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                 // 删除时间
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
