// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePermission = "permissions"

// Permission mapped from table <permissions>
type Permission struct {
	ID          string         `gorm:"column:id;primaryKey;comment:权限ID (UUID)" json:"id"`        // 权限ID (UUID)
	Code        string         `gorm:"column:code;not null;comment:权限代码" json:"code"`             // 权限代码
	Name        string         `gorm:"column:name;not null;comment:权限名称" json:"name"`             // 权限名称
	Resource    string         `gorm:"column:resource;not null;comment:资源类型" json:"resource"`     // 资源类型
	Action      string         `gorm:"column:action;not null;comment:操作类型" json:"action"`         // 操作类型
	Description string         `gorm:"column:description;comment:权限描述" json:"description"`        // 权限描述
	PathPattern string         `gorm:"column:path_pattern;comment:API路径匹配模式" json:"path_pattern"` // API路径匹配模式
	Method      string         `gorm:"column:method;comment:HTTP方法" json:"method"`                // HTTP方法
	IsAPI       bool           `gorm:"column:is_api;default:1;comment:是否为API权限" json:"is_api"`    // 是否为API权限
	IsMenu      bool           `gorm:"column:is_menu;comment:是否菜单权限" json:"is_menu"`              // 是否菜单权限
	MenuIcon    string         `gorm:"column:menu_icon;comment:菜单图标" json:"menu_icon"`            // 菜单图标
	MenuOrder   int64          `gorm:"column:menu_order;comment:菜单排序" json:"menu_order"`          // 菜单排序
	ParentID    string         `gorm:"column:parent_id;comment:父级权限ID" json:"parent_id"`          // 父级权限ID
	Level       int64          `gorm:"column:level;default:100;comment:权限级别" json:"level"`        // 权限级别
	IsActive    bool           `gorm:"column:is_active;default:1;comment:是否启用" json:"is_active"`  // 是否启用
	ExtraData   string         `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`          // 扩展数据
	CreatedAt   time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`          // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`          // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`          // 删除时间
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
