// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRefreshToken = "refresh_tokens"

// RefreshToken mapped from table <refresh_tokens>
type RefreshToken struct {
	ID         string    `gorm:"column:id;primaryKey;comment:令牌ID (UUID)" json:"id"`         // 令牌ID (UUID)
	UserID     string    `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`        // 用户ID
	TokenHash  string    `gorm:"column:token_hash;not null;comment:令牌哈希值" json:"token_hash"` // 令牌哈希值
	ExpiresAt  time.Time `gorm:"column:expires_at;not null;comment:过期时间" json:"expires_at"`  // 过期时间
	IsRevoked  bool      `gorm:"column:is_revoked;not null;comment:是否已撤销" json:"is_revoked"` // 是否已撤销
	RevokedAt  time.Time `gorm:"column:revoked_at;comment:撤销时间" json:"revoked_at"`           // 撤销时间
	DeviceInfo string    `gorm:"column:device_info;comment:设备信息" json:"device_info"`         // 设备信息
	IPAddress  string    `gorm:"column:ip_address;comment:IP地址" json:"ip_address"`           // IP地址
	Location   string    `gorm:"column:location;comment:地理位置" json:"location"`               // 地理位置
	LastUsedAt time.Time `gorm:"column:last_used_at;comment:最后使用时间" json:"last_used_at"`     // 最后使用时间
	UseCount   int64     `gorm:"column:use_count;comment:使用次数" json:"use_count"`             // 使用次数
	CreatedAt  time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`           // 创建时间
}

// TableName RefreshToken's table name
func (*RefreshToken) TableName() string {
	return TableNameRefreshToken
}
