// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRolePermission = "role_permissions"

// RolePermission mapped from table <role_permissions>
type RolePermission struct {
	ID           string    `gorm:"column:id;primaryKey;comment:记录ID (UUID)" json:"id"`              // 记录ID (UUID)
	RoleID       string    `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`             // 角色ID
	PermissionID string    `gorm:"column:permission_id;not null;comment:权限ID" json:"permission_id"` // 权限ID
	IsGranted    bool      `gorm:"column:is_granted;default:1;comment:是否授予" json:"is_granted"`      // 是否授予
	Conditions   string    `gorm:"column:conditions;comment:授权条件" json:"conditions"`                // 授权条件
	CreatedAt    time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                // 创建时间
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
