// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID          string         `gorm:"column:id;primaryKey;comment:角色ID (UUID)" json:"id"`                                                   // 角色ID (UUID)
	Name        string         `gorm:"column:name;not null;comment:角色名称" json:"name"`                                                        // 角色名称
	Code        string         `gorm:"column:code;not null;comment:角色代码 (唯一标识)" json:"code"`                                                 // 角色代码 (唯一标识)
	Type        int32          `gorm:"column:type;default:1;comment:角色类型: 1-超级管理员, 2-审计员, 3-操作员, 4-校管理员, 5-院系管理员, 6-企业HR, 7-学生" json:"type"` // 角色类型: 1-超级管理员, 2-审计员, 3-操作员, 4-校管理员, 5-院系管理员, 6-企业HR, 7-学生
	Description string         `gorm:"column:description;comment:角色描述" json:"description"`                                                   // 角色描述
	Level       int64          `gorm:"column:level;default:100;comment:角色级别 (数值越小级别越高)" json:"level"`                                        // 角色级别 (数值越小级别越高)
	IsSystem    bool           `gorm:"column:is_system;comment:是否系统角色" json:"is_system"`                                                     // 是否系统角色
	IsActive    bool           `gorm:"column:is_active;default:1;comment:是否启用" json:"is_active"`                                             // 是否启用
	Permissions string         `gorm:"column:permissions;comment:权限列表 (JSON数组)" json:"permissions"`                                          // 权限列表 (JSON数组)
	Priority    int64          `gorm:"column:priority;comment:排序优先级" json:"priority"`                                                        // 排序优先级
	CreatedAt   time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                     // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                                     // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                                     // 删除时间
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
