// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSmartContract = "smart_contracts"

// SmartContract mapped from table <smart_contracts>
type SmartContract struct {
	ID              string    `gorm:"column:id;primaryKey;comment:合约ID (UUID)" json:"id"`                    // 合约ID (UUID)
	Name            string    `gorm:"column:name;not null;comment:合约名称" json:"name"`                         // 合约名称
	Code            string    `gorm:"column:code;not null;comment:合约代码 (唯一标识)" json:"code"`                  // 合约代码 (唯一标识)
	NetworkID       string    `gorm:"column:network_id;not null;comment:部署网络ID" json:"network_id"`           // 部署网络ID
	ContractAddress string    `gorm:"column:contract_address;not null;comment:合约地址" json:"contract_address"` // 合约地址
	Abi             string    `gorm:"column:abi;comment:ABI接口定义" json:"abi"`                                 // ABI接口定义
	Bytecode        string    `gorm:"column:bytecode;comment:字节码" json:"bytecode"`                           // 字节码
	Version         string    `gorm:"column:version;comment:合约版本" json:"version"`                            // 合约版本
	DeployerAddress string    `gorm:"column:deployer_address;comment:部署者地址" json:"deployer_address"`         // 部署者地址
	DeployedAt      time.Time `gorm:"column:deployed_at;comment:部署时间" json:"deployed_at"`                    // 部署时间
	Status          int32     `gorm:"column:status;default:1;comment:状态: 1-正常, 2-停用, 3-已废弃" json:"status"`   // 状态: 1-正常, 2-停用, 3-已废弃
	IsVerified      bool      `gorm:"column:is_verified;comment:是否已验证源码" json:"is_verified"`                 // 是否已验证源码
	VerifiedAt      time.Time `gorm:"column:verified_at;comment:验证时间" json:"verified_at"`                    // 验证时间
	ExtraData       string    `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`                      // 扩展数据
	CreatedAt       time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                      // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                      // 更新时间
}

// TableName SmartContract's table name
func (*SmartContract) TableName() string {
	return TableNameSmartContract
}
