// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemConfig = "system_configs"

// SystemConfig mapped from table <system_configs>
type SystemConfig struct {
	ID          string    `gorm:"column:id;primaryKey;comment:配置ID (UUID)" json:"id"`                                  // 配置ID (UUID)
	Key         string    `gorm:"column:key;not null;comment:配置键 (唯一)" json:"key"`                                     // 配置键 (唯一)
	Value       string    `gorm:"column:value;not null;comment:配置值" json:"value"`                                      // 配置值
	Type        string    `gorm:"column:type;default:string;comment:配置类型: string, integer, boolean, json" json:"type"` // 配置类型: string, integer, boolean, json
	Description string    `gorm:"column:description;comment:配置描述" json:"description"`                                  // 配置描述
	Category    string    `gorm:"column:category;default:general;comment:配置分类" json:"category"`                        // 配置分类
	IsEncrypted bool      `gorm:"column:is_encrypted;comment:是否加密存储" json:"is_encrypted"`                              // 是否加密存储
	IsEditable  bool      `gorm:"column:is_editable;default:1;comment:是否可编辑" json:"is_editable"`                       // 是否可编辑
	SortOrder   int64     `gorm:"column:sort_order;comment:排序序号" json:"sort_order"`                                    // 排序序号
	CreatedAt   time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                    // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                    // 更新时间
}

// TableName SystemConfig's table name
func (*SystemConfig) TableName() string {
	return TableNameSystemConfig
}
