// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID               string         `gorm:"column:id;primaryKey;comment:用户ID (UUID)" json:"id"`                              // 用户ID (UUID)
	Username         string         `gorm:"column:username;not null;comment:用户名" json:"username"`                            // 用户名
	Email            string         `gorm:"column:email;not null;comment:邮箱地址" json:"email"`                                 // 邮箱地址
	Phone            string         `gorm:"column:phone;comment:手机号" json:"phone"`                                           // 手机号
	PasswordHash     string         `gorm:"column:password_hash;not null;comment:加密后的密码哈希" json:"password_hash"`             // 加密后的密码哈希
	Salt             string         `gorm:"column:salt;comment:密码盐值" json:"salt"`                                            // 密码盐值
	Status           int32          `gorm:"column:status;default:1;comment:用户状态: 1-正常, 2-禁用, 3-待审核, 4-锁定" json:"status"`     // 用户状态: 1-正常, 2-禁用, 3-待审核, 4-锁定
	UserType         int32          `gorm:"column:user_type;default:1;comment:用户类型: 1-普通用户, 2-管理员, 3-系统用户" json:"user_type"` // 用户类型: 1-普通用户, 2-管理员, 3-系统用户
	Source           int32          `gorm:"column:source;default:1;comment:注册来源: 1-注册, 2-导入, 3-第三方, 4-API" json:"source"`    // 注册来源: 1-注册, 2-导入, 3-第三方, 4-API
	RealName         string         `gorm:"column:real_name;comment:真实姓名" json:"real_name"`                                  // 真实姓名
	Nickname         string         `gorm:"column:nickname;comment:昵称" json:"nickname"`                                      // 昵称
	AvatarURL        string         `gorm:"column:avatar_url;comment:头像URL" json:"avatar_url"`                               // 头像URL
	Gender           int32          `gorm:"column:gender;comment:性别: 0-未知, 1-男, 2-女" json:"gender"`                          // 性别: 0-未知, 1-男, 2-女
	BirthDate        time.Time      `gorm:"column:birth_date;comment:出生日期" json:"birth_date"`                                // 出生日期
	IDCardNumber     string         `gorm:"column:id_card_number;comment:身份证号" json:"id_card_number"`                        // 身份证号
	Bio              string         `gorm:"column:bio;comment:个人简介" json:"bio"`                                              // 个人简介
	Address          string         `gorm:"column:address;comment:地址" json:"address"`                                        // 地址
	LastLoginAt      time.Time      `gorm:"column:last_login_at;comment:最后登录时间" json:"last_login_at"`                        // 最后登录时间
	LastLoginIP      string         `gorm:"column:last_login_ip;comment:最后登录IP" json:"last_login_ip"`                        // 最后登录IP
	LoginCount       int64          `gorm:"column:login_count;comment:登录次数" json:"login_count"`                              // 登录次数
	FailedAttempts   int32          `gorm:"column:failed_attempts;comment:失败尝试次数" json:"failed_attempts"`                    // 失败尝试次数
	LockedUntil      time.Time      `gorm:"column:locked_until;comment:锁定截止时间" json:"locked_until"`                          // 锁定截止时间
	EmailVerified    bool           `gorm:"column:email_verified;comment:邮箱是否已验证" json:"email_verified"`                     // 邮箱是否已验证
	PhoneVerified    bool           `gorm:"column:phone_verified;comment:手机是否已验证" json:"phone_verified"`                     // 手机是否已验证
	TwoFactorEnabled bool           `gorm:"column:two_factor_enabled;comment:是否启用双因素认证" json:"two_factor_enabled"`           // 是否启用双因素认证
	TwoFactorSecret  string         `gorm:"column:two_factor_secret;comment:双因素认证密钥" json:"two_factor_secret"`               // 双因素认证密钥
	ExtraData        string         `gorm:"column:extra_data;comment:扩展数据" json:"extra_data"`                                // 扩展数据
	CreatedAt        time.Time      `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                // 创建时间
	UpdatedAt        time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                // 删除时间
	Version          int64          `gorm:"column:version;default:1;comment:版本号 (乐观锁)" json:"version"`                       // 版本号 (乐观锁)
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
