// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRole = "user_roles"

// UserRole mapped from table <user_roles>
type UserRole struct {
	ID        string    `gorm:"column:id;primaryKey;comment:记录ID (UUID)" json:"id"`       // 记录ID (UUID)
	UserID    string    `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`      // 用户ID
	RoleID    string    `gorm:"column:role_id;not null;comment:角色ID" json:"role_id"`      // 角色ID
	GrantedAt time.Time `gorm:"column:granted_at;comment:授权时间" json:"granted_at"`         // 授权时间
	GrantedBy string    `gorm:"column:granted_by;comment:授权人ID" json:"granted_by"`        // 授权人ID
	ExpiresAt time.Time `gorm:"column:expires_at;comment:过期时间" json:"expires_at"`         // 过期时间
	IsActive  bool      `gorm:"column:is_active;default:1;comment:是否有效" json:"is_active"` // 是否有效
	Remark    string    `gorm:"column:remark;comment:备注" json:"remark"`                   // 备注
	CreatedAt time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`         // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`         // 更新时间
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
