// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: audit.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录日志
type LoginLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"` // 登录地点
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"` // 失败原因
	LoginAt       int64                  `protobuf:"varint,8,opt,name=login_at,json=loginAt,proto3" json:"login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginLog) Reset() {
	*x = LoginLog{}
	mi := &file_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginLog) ProtoMessage() {}

func (x *LoginLog) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginLog.ProtoReflect.Descriptor instead.
func (*LoginLog) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{0}
}

func (x *LoginLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginLog) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LoginLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LoginLog) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *LoginLog) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginLog) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LoginLog) GetLoginAt() int64 {
	if x != nil {
		return x.LoginAt
	}
	return 0
}

// 获取登录日志请求
type GetLoginLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginLogsRequest) Reset() {
	*x = GetLoginLogsRequest{}
	mi := &file_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginLogsRequest) ProtoMessage() {}

func (x *GetLoginLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginLogsRequest.ProtoReflect.Descriptor instead.
func (*GetLoginLogsRequest) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{1}
}

func (x *GetLoginLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetLoginLogsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetLoginLogsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetLoginLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetLoginLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取登录日志响应
type GetLoginLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LoginLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginLogsResponse) Reset() {
	*x = GetLoginLogsResponse{}
	mi := &file_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginLogsResponse) ProtoMessage() {}

func (x *GetLoginLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginLogsResponse.ProtoReflect.Descriptor instead.
func (*GetLoginLogsResponse) Descriptor() ([]byte, []int) {
	return file_audit_proto_rawDescGZIP(), []int{2}
}

func (x *GetLoginLogsResponse) GetLogs() []*LoginLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetLoginLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_audit_proto protoreflect.FileDescriptor

const file_audit_proto_rawDesc = "" +
	"\n" +
	"\vaudit.proto\x12\fapi.proto.v1\"\xcb\x01\n" +
	"\bLoginLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x19\n" +
	"\blogin_at\x18\b \x01(\x03R\aloginAt\"\x99\x01\n" +
	"\x13GetLoginLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"X\n" +
	"\x14GetLoginLogsResponse\x12*\n" +
	"\x04logs\x18\x01 \x03(\v2\x16.api.proto.v1.LoginLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2e\n" +
	"\fAuditService\x12U\n" +
	"\fGetLoginLogs\x12!.api.proto.v1.GetLoginLogsRequest\x1a\".api.proto.v1.GetLoginLogsResponseB,Z*github.com/yz627/edu-chain/api/proto/v1;v1b\x06proto3"

var (
	file_audit_proto_rawDescOnce sync.Once
	file_audit_proto_rawDescData []byte
)

func file_audit_proto_rawDescGZIP() []byte {
	file_audit_proto_rawDescOnce.Do(func() {
		file_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)))
	})
	return file_audit_proto_rawDescData
}

var file_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_audit_proto_goTypes = []any{
	(*LoginLog)(nil),             // 0: api.proto.v1.LoginLog
	(*GetLoginLogsRequest)(nil),  // 1: api.proto.v1.GetLoginLogsRequest
	(*GetLoginLogsResponse)(nil), // 2: api.proto.v1.GetLoginLogsResponse
}
var file_audit_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.GetLoginLogsResponse.logs:type_name -> api.proto.v1.LoginLog
	1, // 1: api.proto.v1.AuditService.GetLoginLogs:input_type -> api.proto.v1.GetLoginLogsRequest
	2, // 2: api.proto.v1.AuditService.GetLoginLogs:output_type -> api.proto.v1.GetLoginLogsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_audit_proto_init() }
func file_audit_proto_init() {
	if File_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_proto_rawDesc), len(file_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audit_proto_goTypes,
		DependencyIndexes: file_audit_proto_depIdxs,
		MessageInfos:      file_audit_proto_msgTypes,
	}.Build()
	File_audit_proto = out.File
	file_audit_proto_goTypes = nil
	file_audit_proto_depIdxs = nil
}
