// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: organization.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 组织类型
type OrganizationType int32

const (
	OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED OrganizationType = 0
	OrganizationType_ORGANIZATION_TYPE_SUPERVISOR  OrganizationType = 1 // 监管机构
	OrganizationType_ORGANIZATION_TYPE_UNIVERSITY  OrganizationType = 2 // 高校
	OrganizationType_ORGANIZATION_TYPE_COMPANY     OrganizationType = 3 // 企业
	OrganizationType_ORGANIZATION_TYPE_GOVERNMENT  OrganizationType = 4 // 政府机构
	OrganizationType_ORGANIZATION_TYPE_OTHER       OrganizationType = 5 // 其他
)

// Enum value maps for OrganizationType.
var (
	OrganizationType_name = map[int32]string{
		0: "ORGANIZATION_TYPE_UNSPECIFIED",
		1: "ORGANIZATION_TYPE_SUPERVISOR",
		2: "ORGANIZATION_TYPE_UNIVERSITY",
		3: "ORGANIZATION_TYPE_COMPANY",
		4: "ORGANIZATION_TYPE_GOVERNMENT",
		5: "ORGANIZATION_TYPE_OTHER",
	}
	OrganizationType_value = map[string]int32{
		"ORGANIZATION_TYPE_UNSPECIFIED": 0,
		"ORGANIZATION_TYPE_SUPERVISOR":  1,
		"ORGANIZATION_TYPE_UNIVERSITY":  2,
		"ORGANIZATION_TYPE_COMPANY":     3,
		"ORGANIZATION_TYPE_GOVERNMENT":  4,
		"ORGANIZATION_TYPE_OTHER":       5,
	}
)

func (x OrganizationType) Enum() *OrganizationType {
	p := new(OrganizationType)
	*p = x
	return p
}

func (x OrganizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_organization_proto_enumTypes[0].Descriptor()
}

func (OrganizationType) Type() protoreflect.EnumType {
	return &file_organization_proto_enumTypes[0]
}

func (x OrganizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrganizationType.Descriptor instead.
func (OrganizationType) EnumDescriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

// 组织（高校/机构）
type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 组织名称
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"` // 组织代码（高校代码等）
	Type          OrganizationType       `protobuf:"varint,4,opt,name=type,proto3,enum=api.proto.v1.OrganizationType" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                               // 地址
	Website       string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`                               // 网站
	ContactName   string                 `protobuf:"bytes,7,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`    // 联系人
	ContactPhone  string                 `protobuf:"bytes,8,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"` // 联系电话
	ContactEmail  string                 `protobuf:"bytes,9,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"` // 联系邮箱
	Logo          string                 `protobuf:"bytes,10,opt,name=logo,proto3" json:"logo,omitempty"`                                    // Logo URL
	IsActive      bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Organization) GetType() OrganizationType {
	if x != nil {
		return x.Type
	}
	return OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED
}

func (x *Organization) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Organization) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Organization) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *Organization) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *Organization) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Organization) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Organization) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Organization) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Organization) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建组织请求
type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Type          OrganizationType       `protobuf:"varint,3,opt,name=type,proto3,enum=api.proto.v1.OrganizationType" json:"type,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Website       string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	ContactName   string                 `protobuf:"bytes,6,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,7,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,8,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateOrganizationRequest) GetType() OrganizationType {
	if x != nil {
		return x.Type
	}
	return OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED
}

func (x *CreateOrganizationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateOrganizationRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CreateOrganizationRequest) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *CreateOrganizationRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *CreateOrganizationRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

// 更新组织请求
type UpdateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Website       string                 `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	ContactName   string                 `protobuf:"bytes,5,opt,name=contact_name,json=contactName,proto3" json:"contact_name,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,6,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,7,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Logo          string                 `protobuf:"bytes,8,opt,name=logo,proto3" json:"logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetContactName() string {
	if x != nil {
		return x.ContactName
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

// 组织用户关联
type OrganizationUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Department     string                 `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`                 // 部门
	Position       string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`                     // 职位
	IsPrimary      bool                   `protobuf:"varint,5,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"` // 是否主组织
	JoinedAt       int64                  `protobuf:"varint,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrganizationUser) Reset() {
	*x = OrganizationUser{}
	mi := &file_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationUser) ProtoMessage() {}

func (x *OrganizationUser) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationUser.ProtoReflect.Descriptor instead.
func (*OrganizationUser) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{3}
}

func (x *OrganizationUser) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *OrganizationUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrganizationUser) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *OrganizationUser) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *OrganizationUser) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *OrganizationUser) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

// 添加组织成员请求
type AddOrganizationMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Department     string                 `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Position       string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddOrganizationMemberRequest) Reset() {
	*x = AddOrganizationMemberRequest{}
	mi := &file_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrganizationMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrganizationMemberRequest) ProtoMessage() {}

func (x *AddOrganizationMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrganizationMemberRequest.ProtoReflect.Descriptor instead.
func (*AddOrganizationMemberRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{4}
}

func (x *AddOrganizationMemberRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AddOrganizationMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddOrganizationMemberRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *AddOrganizationMemberRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

// 分页查询组织请求
type ListOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Type          OrganizationType       `protobuf:"varint,4,opt,name=type,proto3,enum=api.proto.v1.OrganizationType" json:"type,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrganizationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrganizationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrganizationsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListOrganizationsRequest) GetType() OrganizationType {
	if x != nil {
		return x.Type
	}
	return OrganizationType_ORGANIZATION_TYPE_UNSPECIFIED
}

func (x *ListOrganizationsRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// 分页查询组织响应
type ListOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrganizationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrganizationsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取组织成员请求
type GetOrganizationMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page           int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword        string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizationMembersRequest) Reset() {
	*x = GetOrganizationMembersRequest{}
	mi := &file_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationMembersRequest) ProtoMessage() {}

func (x *GetOrganizationMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationMembersRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationMembersRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrganizationMembersRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetOrganizationMembersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrganizationMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetOrganizationMembersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// 获取组织请求
type GetOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrganizationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取组织成员响应
type GetOrganizationMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 用户ID列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationMembersResponse) Reset() {
	*x = GetOrganizationMembersResponse{}
	mi := &file_organization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationMembersResponse) ProtoMessage() {}

func (x *GetOrganizationMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationMembersResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationMembersResponse) Descriptor() ([]byte, []int) {
	return file_organization_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrganizationMembersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetOrganizationMembersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_organization_proto protoreflect.FileDescriptor

const file_organization_proto_rawDesc = "" +
	"\n" +
	"\x12organization.proto\x12\fapi.proto.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x03\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x122\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1e.api.proto.v1.OrganizationTypeR\x04type\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12!\n" +
	"\fcontact_name\x18\a \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\b \x01(\tR\fcontactPhone\x12#\n" +
	"\rcontact_email\x18\t \x01(\tR\fcontactEmail\x12\x12\n" +
	"\x04logo\x18\n" +
	" \x01(\tR\x04logo\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\"\x98\x02\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.api.proto.v1.OrganizationTypeR\x04type\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12!\n" +
	"\fcontact_name\x18\x06 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\a \x01(\tR\fcontactPhone\x12#\n" +
	"\rcontact_email\x18\b \x01(\tR\fcontactEmail\"\xf4\x01\n" +
	"\x19UpdateOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x18\n" +
	"\awebsite\x18\x04 \x01(\tR\awebsite\x12!\n" +
	"\fcontact_name\x18\x05 \x01(\tR\vcontactName\x12#\n" +
	"\rcontact_phone\x18\x06 \x01(\tR\fcontactPhone\x12#\n" +
	"\rcontact_email\x18\a \x01(\tR\fcontactEmail\x12\x12\n" +
	"\x04logo\x18\b \x01(\tR\x04logo\"\xcc\x01\n" +
	"\x10OrganizationUser\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"department\x18\x03 \x01(\tR\n" +
	"department\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x05 \x01(\bR\tisPrimary\x12\x1b\n" +
	"\tjoined_at\x18\x06 \x01(\x03R\bjoinedAt\"\x9c\x01\n" +
	"\x1cAddOrganizationMemberRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"department\x18\x03 \x01(\tR\n" +
	"department\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\"\xb6\x01\n" +
	"\x18ListOrganizationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x122\n" +
	"\x04type\x18\x04 \x01(\x0e2\x1e.api.proto.v1.OrganizationTypeR\x04type\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"\xa4\x01\n" +
	"\x19ListOrganizationsResponse\x12@\n" +
	"\rorganizations\x18\x01 \x03(\v2\x1a.api.proto.v1.OrganizationR\rorganizations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x93\x01\n" +
	"\x1dGetOrganizationMembersRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\"(\n" +
	"\x16GetOrganizationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x1eGetOrganizationMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*\xd7\x01\n" +
	"\x10OrganizationType\x12!\n" +
	"\x1dORGANIZATION_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cORGANIZATION_TYPE_SUPERVISOR\x10\x01\x12 \n" +
	"\x1cORGANIZATION_TYPE_UNIVERSITY\x10\x02\x12\x1d\n" +
	"\x19ORGANIZATION_TYPE_COMPANY\x10\x03\x12 \n" +
	"\x1cORGANIZATION_TYPE_GOVERNMENT\x10\x04\x12\x1b\n" +
	"\x17ORGANIZATION_TYPE_OTHER\x10\x052\xb8\x05\n" +
	"\x13OrganizationService\x12Y\n" +
	"\x12CreateOrganization\x12'.api.proto.v1.CreateOrganizationRequest\x1a\x1a.api.proto.v1.Organization\x12Y\n" +
	"\x12UpdateOrganization\x12'.api.proto.v1.UpdateOrganizationRequest\x1a\x1a.api.proto.v1.Organization\x12d\n" +
	"\x11ListOrganizations\x12&.api.proto.v1.ListOrganizationsRequest\x1a'.api.proto.v1.ListOrganizationsResponse\x12S\n" +
	"\x0fGetOrganization\x12$.api.proto.v1.GetOrganizationRequest\x1a\x1a.api.proto.v1.Organization\x12[\n" +
	"\x15AddOrganizationMember\x12*.api.proto.v1.AddOrganizationMemberRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x18RemoveOrganizationMember\x12*.api.proto.v1.AddOrganizationMemberRequest\x1a\x16.google.protobuf.Empty\x12s\n" +
	"\x16GetOrganizationMembers\x12+.api.proto.v1.GetOrganizationMembersRequest\x1a,.api.proto.v1.GetOrganizationMembersResponseB,Z*github.com/yz627/edu-chain/api/proto/v1;v1b\x06proto3"

var (
	file_organization_proto_rawDescOnce sync.Once
	file_organization_proto_rawDescData []byte
)

func file_organization_proto_rawDescGZIP() []byte {
	file_organization_proto_rawDescOnce.Do(func() {
		file_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)))
	})
	return file_organization_proto_rawDescData
}

var file_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_organization_proto_goTypes = []any{
	(OrganizationType)(0),                  // 0: api.proto.v1.OrganizationType
	(*Organization)(nil),                   // 1: api.proto.v1.Organization
	(*CreateOrganizationRequest)(nil),      // 2: api.proto.v1.CreateOrganizationRequest
	(*UpdateOrganizationRequest)(nil),      // 3: api.proto.v1.UpdateOrganizationRequest
	(*OrganizationUser)(nil),               // 4: api.proto.v1.OrganizationUser
	(*AddOrganizationMemberRequest)(nil),   // 5: api.proto.v1.AddOrganizationMemberRequest
	(*ListOrganizationsRequest)(nil),       // 6: api.proto.v1.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil),      // 7: api.proto.v1.ListOrganizationsResponse
	(*GetOrganizationMembersRequest)(nil),  // 8: api.proto.v1.GetOrganizationMembersRequest
	(*GetOrganizationRequest)(nil),         // 9: api.proto.v1.GetOrganizationRequest
	(*GetOrganizationMembersResponse)(nil), // 10: api.proto.v1.GetOrganizationMembersResponse
	(*emptypb.Empty)(nil),                  // 11: google.protobuf.Empty
}
var file_organization_proto_depIdxs = []int32{
	0,  // 0: api.proto.v1.Organization.type:type_name -> api.proto.v1.OrganizationType
	0,  // 1: api.proto.v1.CreateOrganizationRequest.type:type_name -> api.proto.v1.OrganizationType
	0,  // 2: api.proto.v1.ListOrganizationsRequest.type:type_name -> api.proto.v1.OrganizationType
	1,  // 3: api.proto.v1.ListOrganizationsResponse.organizations:type_name -> api.proto.v1.Organization
	2,  // 4: api.proto.v1.OrganizationService.CreateOrganization:input_type -> api.proto.v1.CreateOrganizationRequest
	3,  // 5: api.proto.v1.OrganizationService.UpdateOrganization:input_type -> api.proto.v1.UpdateOrganizationRequest
	6,  // 6: api.proto.v1.OrganizationService.ListOrganizations:input_type -> api.proto.v1.ListOrganizationsRequest
	9,  // 7: api.proto.v1.OrganizationService.GetOrganization:input_type -> api.proto.v1.GetOrganizationRequest
	5,  // 8: api.proto.v1.OrganizationService.AddOrganizationMember:input_type -> api.proto.v1.AddOrganizationMemberRequest
	5,  // 9: api.proto.v1.OrganizationService.RemoveOrganizationMember:input_type -> api.proto.v1.AddOrganizationMemberRequest
	8,  // 10: api.proto.v1.OrganizationService.GetOrganizationMembers:input_type -> api.proto.v1.GetOrganizationMembersRequest
	1,  // 11: api.proto.v1.OrganizationService.CreateOrganization:output_type -> api.proto.v1.Organization
	1,  // 12: api.proto.v1.OrganizationService.UpdateOrganization:output_type -> api.proto.v1.Organization
	7,  // 13: api.proto.v1.OrganizationService.ListOrganizations:output_type -> api.proto.v1.ListOrganizationsResponse
	1,  // 14: api.proto.v1.OrganizationService.GetOrganization:output_type -> api.proto.v1.Organization
	11, // 15: api.proto.v1.OrganizationService.AddOrganizationMember:output_type -> google.protobuf.Empty
	11, // 16: api.proto.v1.OrganizationService.RemoveOrganizationMember:output_type -> google.protobuf.Empty
	10, // 17: api.proto.v1.OrganizationService.GetOrganizationMembers:output_type -> api.proto.v1.GetOrganizationMembersResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_organization_proto_init() }
func file_organization_proto_init() {
	if File_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_proto_rawDesc), len(file_organization_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_proto_goTypes,
		DependencyIndexes: file_organization_proto_depIdxs,
		EnumInfos:         file_organization_proto_enumTypes,
		MessageInfos:      file_organization_proto_msgTypes,
	}.Build()
	File_organization_proto = out.File
	file_organization_proto_goTypes = nil
	file_organization_proto_depIdxs = nil
}
