// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yz626/edu-chain/internal/data/repository/model"
)

func newBlockchainTransaction(db *gorm.DB, opts ...gen.DOOption) blockchainTransaction {
	_blockchainTransaction := blockchainTransaction{}

	_blockchainTransaction.blockchainTransactionDo.UseDB(db, opts...)
	_blockchainTransaction.blockchainTransactionDo.UseModel(&model.BlockchainTransaction{})

	tableName := _blockchainTransaction.blockchainTransactionDo.TableName()
	_blockchainTransaction.ALL = field.NewAsterisk(tableName)
	_blockchainTransaction.ID = field.NewString(tableName, "id")
	_blockchainTransaction.TxHash = field.NewString(tableName, "tx_hash")
	_blockchainTransaction.NetworkID = field.NewString(tableName, "network_id")
	_blockchainTransaction.CertificateID = field.NewString(tableName, "certificate_id")
	_blockchainTransaction.TxType = field.NewInt32(tableName, "tx_type")
	_blockchainTransaction.FromAddress = field.NewString(tableName, "from_address")
	_blockchainTransaction.ToAddress = field.NewString(tableName, "to_address")
	_blockchainTransaction.Data = field.NewString(tableName, "data")
	_blockchainTransaction.Value = field.NewFloat64(tableName, "value")
	_blockchainTransaction.GasUsed = field.NewInt64(tableName, "gas_used")
	_blockchainTransaction.TxFee = field.NewFloat64(tableName, "tx_fee")
	_blockchainTransaction.BlockNumber = field.NewInt64(tableName, "block_number")
	_blockchainTransaction.BlockHash = field.NewString(tableName, "block_hash")
	_blockchainTransaction.BlockTimestamp = field.NewTime(tableName, "block_timestamp")
	_blockchainTransaction.Confirmations = field.NewInt64(tableName, "confirmations")
	_blockchainTransaction.Status = field.NewInt32(tableName, "status")
	_blockchainTransaction.ErrorMessage = field.NewString(tableName, "error_message")
	_blockchainTransaction.CertHash = field.NewString(tableName, "cert_hash")
	_blockchainTransaction.OwnerAddress = field.NewString(tableName, "owner_address")
	_blockchainTransaction.TokenID = field.NewString(tableName, "token_id")
	_blockchainTransaction.URI = field.NewString(tableName, "uri")
	_blockchainTransaction.CreatedAt = field.NewTime(tableName, "created_at")
	_blockchainTransaction.UpdatedAt = field.NewTime(tableName, "updated_at")

	_blockchainTransaction.fillFieldMap()

	return _blockchainTransaction
}

type blockchainTransaction struct {
	blockchainTransactionDo blockchainTransactionDo

	ALL            field.Asterisk
	ID             field.String  // 交易ID (UUID)
	TxHash         field.String  // 交易哈希 (唯一)
	NetworkID      field.String  // 区块链网络ID
	CertificateID  field.String  // 关联证书ID
	TxType         field.Int32   // 交易类型: 1-存证, 2-撤销, 3-查询, 4-转让
	FromAddress    field.String  // 发起方地址
	ToAddress      field.String  // 接收方地址
	Data           field.String  // 交易数据
	Value          field.Float64 // 交易金额
	GasUsed        field.Int64   // Gas消耗
	TxFee          field.Float64 // 交易手续费
	BlockNumber    field.Int64   // 区块高度
	BlockHash      field.String  // 区块哈希
	BlockTimestamp field.Time    // 区块时间戳
	Confirmations  field.Int64   // 确认数
	Status         field.Int32   // 交易状态: 1-待处理, 2-处理中, 3-成功, 4-失败, 5-超时
	ErrorMessage   field.String  // 错误信息
	CertHash       field.String  // 证书数据哈希
	OwnerAddress   field.String  // 所有者区块链地址
	TokenID        field.String  // NFT Token ID
	URI            field.String  // 元数据URI
	CreatedAt      field.Time    // 创建时间
	UpdatedAt      field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (b blockchainTransaction) Table(newTableName string) *blockchainTransaction {
	b.blockchainTransactionDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b blockchainTransaction) As(alias string) *blockchainTransaction {
	b.blockchainTransactionDo.DO = *(b.blockchainTransactionDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *blockchainTransaction) updateTableName(table string) *blockchainTransaction {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewString(table, "id")
	b.TxHash = field.NewString(table, "tx_hash")
	b.NetworkID = field.NewString(table, "network_id")
	b.CertificateID = field.NewString(table, "certificate_id")
	b.TxType = field.NewInt32(table, "tx_type")
	b.FromAddress = field.NewString(table, "from_address")
	b.ToAddress = field.NewString(table, "to_address")
	b.Data = field.NewString(table, "data")
	b.Value = field.NewFloat64(table, "value")
	b.GasUsed = field.NewInt64(table, "gas_used")
	b.TxFee = field.NewFloat64(table, "tx_fee")
	b.BlockNumber = field.NewInt64(table, "block_number")
	b.BlockHash = field.NewString(table, "block_hash")
	b.BlockTimestamp = field.NewTime(table, "block_timestamp")
	b.Confirmations = field.NewInt64(table, "confirmations")
	b.Status = field.NewInt32(table, "status")
	b.ErrorMessage = field.NewString(table, "error_message")
	b.CertHash = field.NewString(table, "cert_hash")
	b.OwnerAddress = field.NewString(table, "owner_address")
	b.TokenID = field.NewString(table, "token_id")
	b.URI = field.NewString(table, "uri")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")

	b.fillFieldMap()

	return b
}

func (b *blockchainTransaction) WithContext(ctx context.Context) IBlockchainTransactionDo {
	return b.blockchainTransactionDo.WithContext(ctx)
}

func (b blockchainTransaction) TableName() string { return b.blockchainTransactionDo.TableName() }

func (b blockchainTransaction) Alias() string { return b.blockchainTransactionDo.Alias() }

func (b blockchainTransaction) Columns(cols ...field.Expr) gen.Columns {
	return b.blockchainTransactionDo.Columns(cols...)
}

func (b *blockchainTransaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *blockchainTransaction) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 23)
	b.fieldMap["id"] = b.ID
	b.fieldMap["tx_hash"] = b.TxHash
	b.fieldMap["network_id"] = b.NetworkID
	b.fieldMap["certificate_id"] = b.CertificateID
	b.fieldMap["tx_type"] = b.TxType
	b.fieldMap["from_address"] = b.FromAddress
	b.fieldMap["to_address"] = b.ToAddress
	b.fieldMap["data"] = b.Data
	b.fieldMap["value"] = b.Value
	b.fieldMap["gas_used"] = b.GasUsed
	b.fieldMap["tx_fee"] = b.TxFee
	b.fieldMap["block_number"] = b.BlockNumber
	b.fieldMap["block_hash"] = b.BlockHash
	b.fieldMap["block_timestamp"] = b.BlockTimestamp
	b.fieldMap["confirmations"] = b.Confirmations
	b.fieldMap["status"] = b.Status
	b.fieldMap["error_message"] = b.ErrorMessage
	b.fieldMap["cert_hash"] = b.CertHash
	b.fieldMap["owner_address"] = b.OwnerAddress
	b.fieldMap["token_id"] = b.TokenID
	b.fieldMap["uri"] = b.URI
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
}

func (b blockchainTransaction) clone(db *gorm.DB) blockchainTransaction {
	b.blockchainTransactionDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b blockchainTransaction) replaceDB(db *gorm.DB) blockchainTransaction {
	b.blockchainTransactionDo.ReplaceDB(db)
	return b
}

type blockchainTransactionDo struct{ gen.DO }

type IBlockchainTransactionDo interface {
	gen.SubQuery
	Debug() IBlockchainTransactionDo
	WithContext(ctx context.Context) IBlockchainTransactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBlockchainTransactionDo
	WriteDB() IBlockchainTransactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBlockchainTransactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBlockchainTransactionDo
	Not(conds ...gen.Condition) IBlockchainTransactionDo
	Or(conds ...gen.Condition) IBlockchainTransactionDo
	Select(conds ...field.Expr) IBlockchainTransactionDo
	Where(conds ...gen.Condition) IBlockchainTransactionDo
	Order(conds ...field.Expr) IBlockchainTransactionDo
	Distinct(cols ...field.Expr) IBlockchainTransactionDo
	Omit(cols ...field.Expr) IBlockchainTransactionDo
	Join(table schema.Tabler, on ...field.Expr) IBlockchainTransactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBlockchainTransactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBlockchainTransactionDo
	Group(cols ...field.Expr) IBlockchainTransactionDo
	Having(conds ...gen.Condition) IBlockchainTransactionDo
	Limit(limit int) IBlockchainTransactionDo
	Offset(offset int) IBlockchainTransactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBlockchainTransactionDo
	Unscoped() IBlockchainTransactionDo
	Create(values ...*model.BlockchainTransaction) error
	CreateInBatches(values []*model.BlockchainTransaction, batchSize int) error
	Save(values ...*model.BlockchainTransaction) error
	First() (*model.BlockchainTransaction, error)
	Take() (*model.BlockchainTransaction, error)
	Last() (*model.BlockchainTransaction, error)
	Find() ([]*model.BlockchainTransaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BlockchainTransaction, err error)
	FindInBatches(result *[]*model.BlockchainTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BlockchainTransaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBlockchainTransactionDo
	Assign(attrs ...field.AssignExpr) IBlockchainTransactionDo
	Joins(fields ...field.RelationField) IBlockchainTransactionDo
	Preload(fields ...field.RelationField) IBlockchainTransactionDo
	FirstOrInit() (*model.BlockchainTransaction, error)
	FirstOrCreate() (*model.BlockchainTransaction, error)
	FindByPage(offset int, limit int) (result []*model.BlockchainTransaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBlockchainTransactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b blockchainTransactionDo) Debug() IBlockchainTransactionDo {
	return b.withDO(b.DO.Debug())
}

func (b blockchainTransactionDo) WithContext(ctx context.Context) IBlockchainTransactionDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b blockchainTransactionDo) ReadDB() IBlockchainTransactionDo {
	return b.Clauses(dbresolver.Read)
}

func (b blockchainTransactionDo) WriteDB() IBlockchainTransactionDo {
	return b.Clauses(dbresolver.Write)
}

func (b blockchainTransactionDo) Session(config *gorm.Session) IBlockchainTransactionDo {
	return b.withDO(b.DO.Session(config))
}

func (b blockchainTransactionDo) Clauses(conds ...clause.Expression) IBlockchainTransactionDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b blockchainTransactionDo) Returning(value interface{}, columns ...string) IBlockchainTransactionDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b blockchainTransactionDo) Not(conds ...gen.Condition) IBlockchainTransactionDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b blockchainTransactionDo) Or(conds ...gen.Condition) IBlockchainTransactionDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b blockchainTransactionDo) Select(conds ...field.Expr) IBlockchainTransactionDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b blockchainTransactionDo) Where(conds ...gen.Condition) IBlockchainTransactionDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b blockchainTransactionDo) Order(conds ...field.Expr) IBlockchainTransactionDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b blockchainTransactionDo) Distinct(cols ...field.Expr) IBlockchainTransactionDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b blockchainTransactionDo) Omit(cols ...field.Expr) IBlockchainTransactionDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b blockchainTransactionDo) Join(table schema.Tabler, on ...field.Expr) IBlockchainTransactionDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b blockchainTransactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBlockchainTransactionDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b blockchainTransactionDo) RightJoin(table schema.Tabler, on ...field.Expr) IBlockchainTransactionDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b blockchainTransactionDo) Group(cols ...field.Expr) IBlockchainTransactionDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b blockchainTransactionDo) Having(conds ...gen.Condition) IBlockchainTransactionDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b blockchainTransactionDo) Limit(limit int) IBlockchainTransactionDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b blockchainTransactionDo) Offset(offset int) IBlockchainTransactionDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b blockchainTransactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBlockchainTransactionDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b blockchainTransactionDo) Unscoped() IBlockchainTransactionDo {
	return b.withDO(b.DO.Unscoped())
}

func (b blockchainTransactionDo) Create(values ...*model.BlockchainTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b blockchainTransactionDo) CreateInBatches(values []*model.BlockchainTransaction, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b blockchainTransactionDo) Save(values ...*model.BlockchainTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b blockchainTransactionDo) First() (*model.BlockchainTransaction, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlockchainTransaction), nil
	}
}

func (b blockchainTransactionDo) Take() (*model.BlockchainTransaction, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlockchainTransaction), nil
	}
}

func (b blockchainTransactionDo) Last() (*model.BlockchainTransaction, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlockchainTransaction), nil
	}
}

func (b blockchainTransactionDo) Find() ([]*model.BlockchainTransaction, error) {
	result, err := b.DO.Find()
	return result.([]*model.BlockchainTransaction), err
}

func (b blockchainTransactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BlockchainTransaction, err error) {
	buf := make([]*model.BlockchainTransaction, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b blockchainTransactionDo) FindInBatches(result *[]*model.BlockchainTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b blockchainTransactionDo) Attrs(attrs ...field.AssignExpr) IBlockchainTransactionDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b blockchainTransactionDo) Assign(attrs ...field.AssignExpr) IBlockchainTransactionDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b blockchainTransactionDo) Joins(fields ...field.RelationField) IBlockchainTransactionDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b blockchainTransactionDo) Preload(fields ...field.RelationField) IBlockchainTransactionDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b blockchainTransactionDo) FirstOrInit() (*model.BlockchainTransaction, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlockchainTransaction), nil
	}
}

func (b blockchainTransactionDo) FirstOrCreate() (*model.BlockchainTransaction, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BlockchainTransaction), nil
	}
}

func (b blockchainTransactionDo) FindByPage(offset int, limit int) (result []*model.BlockchainTransaction, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b blockchainTransactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b blockchainTransactionDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b blockchainTransactionDo) Delete(models ...*model.BlockchainTransaction) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *blockchainTransactionDo) withDO(do gen.Dao) *blockchainTransactionDo {
	b.DO = *do.(*gen.DO)
	return b
}
