// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yz626/edu-chain/internal/data/repository/model"
)

func newCertificateType(db *gorm.DB, opts ...gen.DOOption) certificateType {
	_certificateType := certificateType{}

	_certificateType.certificateTypeDo.UseDB(db, opts...)
	_certificateType.certificateTypeDo.UseModel(&model.CertificateType{})

	tableName := _certificateType.certificateTypeDo.TableName()
	_certificateType.ALL = field.NewAsterisk(tableName)
	_certificateType.ID = field.NewString(tableName, "id")
	_certificateType.Code = field.NewString(tableName, "code")
	_certificateType.Name = field.NewString(tableName, "name")
	_certificateType.Category = field.NewInt32(tableName, "category")
	_certificateType.DegreeLevel = field.NewInt32(tableName, "degree_level")
	_certificateType.Description = field.NewString(tableName, "description")
	_certificateType.IsActive = field.NewBool(tableName, "is_active")
	_certificateType.SortOrder = field.NewInt64(tableName, "sort_order")
	_certificateType.ExtraData = field.NewString(tableName, "extra_data")
	_certificateType.CreatedAt = field.NewTime(tableName, "created_at")
	_certificateType.UpdatedAt = field.NewTime(tableName, "updated_at")

	_certificateType.fillFieldMap()

	return _certificateType
}

type certificateType struct {
	certificateTypeDo certificateTypeDo

	ALL         field.Asterisk
	ID          field.String // 类型ID (UUID)
	Code        field.String // 类型代码 (唯一标识)
	Name        field.String // 类型名称
	Category    field.Int32  // 证书类别: 1-毕业证书, 2-学位证书, 3-成绩单, 4-资格证书, 5-其他
	DegreeLevel field.Int32  // 学位等级: 1-学士, 2-硕士, 3-博士
	Description field.String // 类型描述
	IsActive    field.Bool   // 是否启用
	SortOrder   field.Int64  // 排序序号
	ExtraData   field.String // 扩展数据
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c certificateType) Table(newTableName string) *certificateType {
	c.certificateTypeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c certificateType) As(alias string) *certificateType {
	c.certificateTypeDo.DO = *(c.certificateTypeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *certificateType) updateTableName(table string) *certificateType {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Code = field.NewString(table, "code")
	c.Name = field.NewString(table, "name")
	c.Category = field.NewInt32(table, "category")
	c.DegreeLevel = field.NewInt32(table, "degree_level")
	c.Description = field.NewString(table, "description")
	c.IsActive = field.NewBool(table, "is_active")
	c.SortOrder = field.NewInt64(table, "sort_order")
	c.ExtraData = field.NewString(table, "extra_data")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *certificateType) WithContext(ctx context.Context) ICertificateTypeDo {
	return c.certificateTypeDo.WithContext(ctx)
}

func (c certificateType) TableName() string { return c.certificateTypeDo.TableName() }

func (c certificateType) Alias() string { return c.certificateTypeDo.Alias() }

func (c certificateType) Columns(cols ...field.Expr) gen.Columns {
	return c.certificateTypeDo.Columns(cols...)
}

func (c *certificateType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *certificateType) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["id"] = c.ID
	c.fieldMap["code"] = c.Code
	c.fieldMap["name"] = c.Name
	c.fieldMap["category"] = c.Category
	c.fieldMap["degree_level"] = c.DegreeLevel
	c.fieldMap["description"] = c.Description
	c.fieldMap["is_active"] = c.IsActive
	c.fieldMap["sort_order"] = c.SortOrder
	c.fieldMap["extra_data"] = c.ExtraData
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c certificateType) clone(db *gorm.DB) certificateType {
	c.certificateTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c certificateType) replaceDB(db *gorm.DB) certificateType {
	c.certificateTypeDo.ReplaceDB(db)
	return c
}

type certificateTypeDo struct{ gen.DO }

type ICertificateTypeDo interface {
	gen.SubQuery
	Debug() ICertificateTypeDo
	WithContext(ctx context.Context) ICertificateTypeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICertificateTypeDo
	WriteDB() ICertificateTypeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICertificateTypeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICertificateTypeDo
	Not(conds ...gen.Condition) ICertificateTypeDo
	Or(conds ...gen.Condition) ICertificateTypeDo
	Select(conds ...field.Expr) ICertificateTypeDo
	Where(conds ...gen.Condition) ICertificateTypeDo
	Order(conds ...field.Expr) ICertificateTypeDo
	Distinct(cols ...field.Expr) ICertificateTypeDo
	Omit(cols ...field.Expr) ICertificateTypeDo
	Join(table schema.Tabler, on ...field.Expr) ICertificateTypeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICertificateTypeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICertificateTypeDo
	Group(cols ...field.Expr) ICertificateTypeDo
	Having(conds ...gen.Condition) ICertificateTypeDo
	Limit(limit int) ICertificateTypeDo
	Offset(offset int) ICertificateTypeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICertificateTypeDo
	Unscoped() ICertificateTypeDo
	Create(values ...*model.CertificateType) error
	CreateInBatches(values []*model.CertificateType, batchSize int) error
	Save(values ...*model.CertificateType) error
	First() (*model.CertificateType, error)
	Take() (*model.CertificateType, error)
	Last() (*model.CertificateType, error)
	Find() ([]*model.CertificateType, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CertificateType, err error)
	FindInBatches(result *[]*model.CertificateType, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CertificateType) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICertificateTypeDo
	Assign(attrs ...field.AssignExpr) ICertificateTypeDo
	Joins(fields ...field.RelationField) ICertificateTypeDo
	Preload(fields ...field.RelationField) ICertificateTypeDo
	FirstOrInit() (*model.CertificateType, error)
	FirstOrCreate() (*model.CertificateType, error)
	FindByPage(offset int, limit int) (result []*model.CertificateType, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICertificateTypeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c certificateTypeDo) Debug() ICertificateTypeDo {
	return c.withDO(c.DO.Debug())
}

func (c certificateTypeDo) WithContext(ctx context.Context) ICertificateTypeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c certificateTypeDo) ReadDB() ICertificateTypeDo {
	return c.Clauses(dbresolver.Read)
}

func (c certificateTypeDo) WriteDB() ICertificateTypeDo {
	return c.Clauses(dbresolver.Write)
}

func (c certificateTypeDo) Session(config *gorm.Session) ICertificateTypeDo {
	return c.withDO(c.DO.Session(config))
}

func (c certificateTypeDo) Clauses(conds ...clause.Expression) ICertificateTypeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c certificateTypeDo) Returning(value interface{}, columns ...string) ICertificateTypeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c certificateTypeDo) Not(conds ...gen.Condition) ICertificateTypeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c certificateTypeDo) Or(conds ...gen.Condition) ICertificateTypeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c certificateTypeDo) Select(conds ...field.Expr) ICertificateTypeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c certificateTypeDo) Where(conds ...gen.Condition) ICertificateTypeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c certificateTypeDo) Order(conds ...field.Expr) ICertificateTypeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c certificateTypeDo) Distinct(cols ...field.Expr) ICertificateTypeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c certificateTypeDo) Omit(cols ...field.Expr) ICertificateTypeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c certificateTypeDo) Join(table schema.Tabler, on ...field.Expr) ICertificateTypeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c certificateTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICertificateTypeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c certificateTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) ICertificateTypeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c certificateTypeDo) Group(cols ...field.Expr) ICertificateTypeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c certificateTypeDo) Having(conds ...gen.Condition) ICertificateTypeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c certificateTypeDo) Limit(limit int) ICertificateTypeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c certificateTypeDo) Offset(offset int) ICertificateTypeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c certificateTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICertificateTypeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c certificateTypeDo) Unscoped() ICertificateTypeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c certificateTypeDo) Create(values ...*model.CertificateType) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c certificateTypeDo) CreateInBatches(values []*model.CertificateType, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c certificateTypeDo) Save(values ...*model.CertificateType) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c certificateTypeDo) First() (*model.CertificateType, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateType), nil
	}
}

func (c certificateTypeDo) Take() (*model.CertificateType, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateType), nil
	}
}

func (c certificateTypeDo) Last() (*model.CertificateType, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateType), nil
	}
}

func (c certificateTypeDo) Find() ([]*model.CertificateType, error) {
	result, err := c.DO.Find()
	return result.([]*model.CertificateType), err
}

func (c certificateTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CertificateType, err error) {
	buf := make([]*model.CertificateType, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c certificateTypeDo) FindInBatches(result *[]*model.CertificateType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c certificateTypeDo) Attrs(attrs ...field.AssignExpr) ICertificateTypeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c certificateTypeDo) Assign(attrs ...field.AssignExpr) ICertificateTypeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c certificateTypeDo) Joins(fields ...field.RelationField) ICertificateTypeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c certificateTypeDo) Preload(fields ...field.RelationField) ICertificateTypeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c certificateTypeDo) FirstOrInit() (*model.CertificateType, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateType), nil
	}
}

func (c certificateTypeDo) FirstOrCreate() (*model.CertificateType, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateType), nil
	}
}

func (c certificateTypeDo) FindByPage(offset int, limit int) (result []*model.CertificateType, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c certificateTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c certificateTypeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c certificateTypeDo) Delete(models ...*model.CertificateType) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *certificateTypeDo) withDO(do gen.Dao) *certificateTypeDo {
	c.DO = *do.(*gen.DO)
	return c
}
