// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yz626/edu-chain/internal/data/repository/model"
)

func newCertificateTemplate(db *gorm.DB, opts ...gen.DOOption) certificateTemplate {
	_certificateTemplate := certificateTemplate{}

	_certificateTemplate.certificateTemplateDo.UseDB(db, opts...)
	_certificateTemplate.certificateTemplateDo.UseModel(&model.CertificateTemplate{})

	tableName := _certificateTemplate.certificateTemplateDo.TableName()
	_certificateTemplate.ALL = field.NewAsterisk(tableName)
	_certificateTemplate.ID = field.NewString(tableName, "id")
	_certificateTemplate.Name = field.NewString(tableName, "name")
	_certificateTemplate.Code = field.NewString(tableName, "code")
	_certificateTemplate.TypeID = field.NewString(tableName, "type_id")
	_certificateTemplate.ThumbnailURL = field.NewString(tableName, "thumbnail_url")
	_certificateTemplate.TemplateFileURL = field.NewString(tableName, "template_file_url")
	_certificateTemplate.TemplateData = field.NewString(tableName, "template_data")
	_certificateTemplate.Fields = field.NewString(tableName, "fields")
	_certificateTemplate.IsDefault = field.NewBool(tableName, "is_default")
	_certificateTemplate.IsActive = field.NewBool(tableName, "is_active")
	_certificateTemplate.Version = field.NewInt64(tableName, "version")
	_certificateTemplate.OrganizationID = field.NewString(tableName, "organization_id")
	_certificateTemplate.CreatedBy = field.NewString(tableName, "created_by")
	_certificateTemplate.CreatedAt = field.NewTime(tableName, "created_at")
	_certificateTemplate.UpdatedAt = field.NewTime(tableName, "updated_at")

	_certificateTemplate.fillFieldMap()

	return _certificateTemplate
}

type certificateTemplate struct {
	certificateTemplateDo certificateTemplateDo

	ALL             field.Asterisk
	ID              field.String // 模板ID (UUID)
	Name            field.String // 模板名称
	Code            field.String // 模板代码 (唯一标识)
	TypeID          field.String // 证书类型ID
	ThumbnailURL    field.String // 缩略图URL
	TemplateFileURL field.String // 模板文件URL
	TemplateData    field.String // 模板配置数据
	Fields          field.String // 模板字段配置
	IsDefault       field.Bool   // 是否默认模板
	IsActive        field.Bool   // 是否启用
	Version         field.Int64  // 版本号
	OrganizationID  field.String // 所属组织ID
	CreatedBy       field.String // 创建人ID
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c certificateTemplate) Table(newTableName string) *certificateTemplate {
	c.certificateTemplateDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c certificateTemplate) As(alias string) *certificateTemplate {
	c.certificateTemplateDo.DO = *(c.certificateTemplateDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *certificateTemplate) updateTableName(table string) *certificateTemplate {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Name = field.NewString(table, "name")
	c.Code = field.NewString(table, "code")
	c.TypeID = field.NewString(table, "type_id")
	c.ThumbnailURL = field.NewString(table, "thumbnail_url")
	c.TemplateFileURL = field.NewString(table, "template_file_url")
	c.TemplateData = field.NewString(table, "template_data")
	c.Fields = field.NewString(table, "fields")
	c.IsDefault = field.NewBool(table, "is_default")
	c.IsActive = field.NewBool(table, "is_active")
	c.Version = field.NewInt64(table, "version")
	c.OrganizationID = field.NewString(table, "organization_id")
	c.CreatedBy = field.NewString(table, "created_by")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *certificateTemplate) WithContext(ctx context.Context) ICertificateTemplateDo {
	return c.certificateTemplateDo.WithContext(ctx)
}

func (c certificateTemplate) TableName() string { return c.certificateTemplateDo.TableName() }

func (c certificateTemplate) Alias() string { return c.certificateTemplateDo.Alias() }

func (c certificateTemplate) Columns(cols ...field.Expr) gen.Columns {
	return c.certificateTemplateDo.Columns(cols...)
}

func (c *certificateTemplate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *certificateTemplate) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 15)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
	c.fieldMap["code"] = c.Code
	c.fieldMap["type_id"] = c.TypeID
	c.fieldMap["thumbnail_url"] = c.ThumbnailURL
	c.fieldMap["template_file_url"] = c.TemplateFileURL
	c.fieldMap["template_data"] = c.TemplateData
	c.fieldMap["fields"] = c.Fields
	c.fieldMap["is_default"] = c.IsDefault
	c.fieldMap["is_active"] = c.IsActive
	c.fieldMap["version"] = c.Version
	c.fieldMap["organization_id"] = c.OrganizationID
	c.fieldMap["created_by"] = c.CreatedBy
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c certificateTemplate) clone(db *gorm.DB) certificateTemplate {
	c.certificateTemplateDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c certificateTemplate) replaceDB(db *gorm.DB) certificateTemplate {
	c.certificateTemplateDo.ReplaceDB(db)
	return c
}

type certificateTemplateDo struct{ gen.DO }

type ICertificateTemplateDo interface {
	gen.SubQuery
	Debug() ICertificateTemplateDo
	WithContext(ctx context.Context) ICertificateTemplateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICertificateTemplateDo
	WriteDB() ICertificateTemplateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICertificateTemplateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICertificateTemplateDo
	Not(conds ...gen.Condition) ICertificateTemplateDo
	Or(conds ...gen.Condition) ICertificateTemplateDo
	Select(conds ...field.Expr) ICertificateTemplateDo
	Where(conds ...gen.Condition) ICertificateTemplateDo
	Order(conds ...field.Expr) ICertificateTemplateDo
	Distinct(cols ...field.Expr) ICertificateTemplateDo
	Omit(cols ...field.Expr) ICertificateTemplateDo
	Join(table schema.Tabler, on ...field.Expr) ICertificateTemplateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICertificateTemplateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICertificateTemplateDo
	Group(cols ...field.Expr) ICertificateTemplateDo
	Having(conds ...gen.Condition) ICertificateTemplateDo
	Limit(limit int) ICertificateTemplateDo
	Offset(offset int) ICertificateTemplateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICertificateTemplateDo
	Unscoped() ICertificateTemplateDo
	Create(values ...*model.CertificateTemplate) error
	CreateInBatches(values []*model.CertificateTemplate, batchSize int) error
	Save(values ...*model.CertificateTemplate) error
	First() (*model.CertificateTemplate, error)
	Take() (*model.CertificateTemplate, error)
	Last() (*model.CertificateTemplate, error)
	Find() ([]*model.CertificateTemplate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CertificateTemplate, err error)
	FindInBatches(result *[]*model.CertificateTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CertificateTemplate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICertificateTemplateDo
	Assign(attrs ...field.AssignExpr) ICertificateTemplateDo
	Joins(fields ...field.RelationField) ICertificateTemplateDo
	Preload(fields ...field.RelationField) ICertificateTemplateDo
	FirstOrInit() (*model.CertificateTemplate, error)
	FirstOrCreate() (*model.CertificateTemplate, error)
	FindByPage(offset int, limit int) (result []*model.CertificateTemplate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICertificateTemplateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c certificateTemplateDo) Debug() ICertificateTemplateDo {
	return c.withDO(c.DO.Debug())
}

func (c certificateTemplateDo) WithContext(ctx context.Context) ICertificateTemplateDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c certificateTemplateDo) ReadDB() ICertificateTemplateDo {
	return c.Clauses(dbresolver.Read)
}

func (c certificateTemplateDo) WriteDB() ICertificateTemplateDo {
	return c.Clauses(dbresolver.Write)
}

func (c certificateTemplateDo) Session(config *gorm.Session) ICertificateTemplateDo {
	return c.withDO(c.DO.Session(config))
}

func (c certificateTemplateDo) Clauses(conds ...clause.Expression) ICertificateTemplateDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c certificateTemplateDo) Returning(value interface{}, columns ...string) ICertificateTemplateDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c certificateTemplateDo) Not(conds ...gen.Condition) ICertificateTemplateDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c certificateTemplateDo) Or(conds ...gen.Condition) ICertificateTemplateDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c certificateTemplateDo) Select(conds ...field.Expr) ICertificateTemplateDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c certificateTemplateDo) Where(conds ...gen.Condition) ICertificateTemplateDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c certificateTemplateDo) Order(conds ...field.Expr) ICertificateTemplateDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c certificateTemplateDo) Distinct(cols ...field.Expr) ICertificateTemplateDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c certificateTemplateDo) Omit(cols ...field.Expr) ICertificateTemplateDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c certificateTemplateDo) Join(table schema.Tabler, on ...field.Expr) ICertificateTemplateDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c certificateTemplateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICertificateTemplateDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c certificateTemplateDo) RightJoin(table schema.Tabler, on ...field.Expr) ICertificateTemplateDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c certificateTemplateDo) Group(cols ...field.Expr) ICertificateTemplateDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c certificateTemplateDo) Having(conds ...gen.Condition) ICertificateTemplateDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c certificateTemplateDo) Limit(limit int) ICertificateTemplateDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c certificateTemplateDo) Offset(offset int) ICertificateTemplateDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c certificateTemplateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICertificateTemplateDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c certificateTemplateDo) Unscoped() ICertificateTemplateDo {
	return c.withDO(c.DO.Unscoped())
}

func (c certificateTemplateDo) Create(values ...*model.CertificateTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c certificateTemplateDo) CreateInBatches(values []*model.CertificateTemplate, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c certificateTemplateDo) Save(values ...*model.CertificateTemplate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c certificateTemplateDo) First() (*model.CertificateTemplate, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateTemplate), nil
	}
}

func (c certificateTemplateDo) Take() (*model.CertificateTemplate, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateTemplate), nil
	}
}

func (c certificateTemplateDo) Last() (*model.CertificateTemplate, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateTemplate), nil
	}
}

func (c certificateTemplateDo) Find() ([]*model.CertificateTemplate, error) {
	result, err := c.DO.Find()
	return result.([]*model.CertificateTemplate), err
}

func (c certificateTemplateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CertificateTemplate, err error) {
	buf := make([]*model.CertificateTemplate, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c certificateTemplateDo) FindInBatches(result *[]*model.CertificateTemplate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c certificateTemplateDo) Attrs(attrs ...field.AssignExpr) ICertificateTemplateDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c certificateTemplateDo) Assign(attrs ...field.AssignExpr) ICertificateTemplateDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c certificateTemplateDo) Joins(fields ...field.RelationField) ICertificateTemplateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c certificateTemplateDo) Preload(fields ...field.RelationField) ICertificateTemplateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c certificateTemplateDo) FirstOrInit() (*model.CertificateTemplate, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateTemplate), nil
	}
}

func (c certificateTemplateDo) FirstOrCreate() (*model.CertificateTemplate, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CertificateTemplate), nil
	}
}

func (c certificateTemplateDo) FindByPage(offset int, limit int) (result []*model.CertificateTemplate, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c certificateTemplateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c certificateTemplateDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c certificateTemplateDo) Delete(models ...*model.CertificateTemplate) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *certificateTemplateDo) withDO(do gen.Dao) *certificateTemplateDo {
	c.DO = *do.(*gen.DO)
	return c
}
