// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yz626/edu-chain/internal/data/repository/model"
)

func newCertificate(db *gorm.DB, opts ...gen.DOOption) certificate {
	_certificate := certificate{}

	_certificate.certificateDo.UseDB(db, opts...)
	_certificate.certificateDo.UseModel(&model.Certificate{})

	tableName := _certificate.certificateDo.TableName()
	_certificate.ALL = field.NewAsterisk(tableName)
	_certificate.ID = field.NewString(tableName, "id")
	_certificate.CertificateNo = field.NewString(tableName, "certificate_no")
	_certificate.TypeID = field.NewString(tableName, "type_id")
	_certificate.UserID = field.NewString(tableName, "user_id")
	_certificate.OrganizationID = field.NewString(tableName, "organization_id")
	_certificate.TemplateID = field.NewString(tableName, "template_id")
	_certificate.StudentNo = field.NewString(tableName, "student_no")
	_certificate.Name = field.NewString(tableName, "name")
	_certificate.IDCardNumber = field.NewString(tableName, "id_card_number")
	_certificate.Gender = field.NewInt32(tableName, "gender")
	_certificate.Major = field.NewString(tableName, "major")
	_certificate.MajorCode = field.NewString(tableName, "major_code")
	_certificate.Degree = field.NewInt32(tableName, "degree")
	_certificate.DegreeName = field.NewString(tableName, "degree_name")
	_certificate.EducationLevel = field.NewInt32(tableName, "education_level")
	_certificate.EducationType = field.NewInt32(tableName, "education_type")
	_certificate.EnrollmentDate = field.NewTime(tableName, "enrollment_date")
	_certificate.GraduationDate = field.NewTime(tableName, "graduation_date")
	_certificate.StudyPeriod = field.NewString(tableName, "study_period")
	_certificate.SchoolSystem = field.NewString(tableName, "school_system")
	_certificate.Campus = field.NewString(tableName, "campus")
	_certificate.Gpa = field.NewFloat64(tableName, "gpa")
	_certificate.TotalCredits = field.NewFloat64(tableName, "total_credits")
	_certificate.Status = field.NewInt32(tableName, "status")
	_certificate.IssueDate = field.NewTime(tableName, "issue_date")
	_certificate.ValidFromDate = field.NewTime(tableName, "valid_from_date")
	_certificate.ValidUntilDate = field.NewTime(tableName, "valid_until_date")
	_certificate.BlockchainTxHash = field.NewString(tableName, "blockchain_tx_hash")
	_certificate.BlockchainCertHash = field.NewString(tableName, "blockchain_cert_hash")
	_certificate.BlockchainBlockNo = field.NewInt64(tableName, "blockchain_block_no")
	_certificate.BlockchainTimestamp = field.NewTime(tableName, "blockchain_timestamp")
	_certificate.OnChainStatus = field.NewInt32(tableName, "on_chain_status")
	_certificate.OnChainAt = field.NewTime(tableName, "on_chain_at")
	_certificate.PdfURL = field.NewString(tableName, "pdf_url")
	_certificate.PdfHash = field.NewString(tableName, "pdf_hash")
	_certificate.PdfSignedBy = field.NewString(tableName, "pdf_signed_by")
	_certificate.PdfSignedAt = field.NewTime(tableName, "pdf_signed_at")
	_certificate.SignedBy = field.NewString(tableName, "signed_by")
	_certificate.IssuedBy = field.NewString(tableName, "issued_by")
	_certificate.IssueReason = field.NewString(tableName, "issue_reason")
	_certificate.RevokedAt = field.NewTime(tableName, "revoked_at")
	_certificate.RevokedBy = field.NewString(tableName, "revoked_by")
	_certificate.RevokeReason = field.NewString(tableName, "revoke_reason")
	_certificate.VerificationCount = field.NewInt64(tableName, "verification_count")
	_certificate.LastVerifiedAt = field.NewTime(tableName, "last_verified_at")
	_certificate.ExtraData = field.NewString(tableName, "extra_data")
	_certificate.CreatedAt = field.NewTime(tableName, "created_at")
	_certificate.UpdatedAt = field.NewTime(tableName, "updated_at")
	_certificate.DeletedAt = field.NewField(tableName, "deleted_at")
	_certificate.Version = field.NewInt64(tableName, "version")

	_certificate.fillFieldMap()

	return _certificate
}

type certificate struct {
	certificateDo certificateDo

	ALL                 field.Asterisk
	ID                  field.String  // 证书ID (UUID)
	CertificateNo       field.String  // 证书编号 (唯一)
	TypeID              field.String  // 证书类型ID
	UserID              field.String  // 持有人用户ID
	OrganizationID      field.String  // 发证机构ID
	TemplateID          field.String  // 使用的模板ID
	StudentNo           field.String  // 学号
	Name                field.String  // 证书持有人姓名
	IDCardNumber        field.String  // 身份证号
	Gender              field.Int32   // 性别: 1-男, 2-女
	Major               field.String  // 专业名称
	MajorCode           field.String  // 专业代码
	Degree              field.Int32   // 学位等级: 1-学士, 2-硕士, 3-博士, 4-无学位, 5-专科
	DegreeName          field.String  // 学位名称
	EducationLevel      field.Int32   // 学历层次
	EducationType       field.Int32   // 办学类型: 1-全日制, 2-非全日制, 3-成人教育
	EnrollmentDate      field.Time    // 入学日期
	GraduationDate      field.Time    // 毕业日期
	StudyPeriod         field.String  // 学习期限
	SchoolSystem        field.String  // 学制
	Campus              field.String  // 校区
	Gpa                 field.Float64 // 平均学分绩点
	TotalCredits        field.Float64 // 总学分
	Status              field.Int32   // 证书状态: 1-有效, 2-已撤销, 3-已挂失, 4-草稿, 5-审核中
	IssueDate           field.Time    // 发证日期
	ValidFromDate       field.Time    // 有效开始日期
	ValidUntilDate      field.Time    // 有效结束日期
	BlockchainTxHash    field.String  // 区块链交易哈希
	BlockchainCertHash  field.String  // 证书数据哈希
	BlockchainBlockNo   field.Int64   // 区块链块号
	BlockchainTimestamp field.Time    // 区块链时间戳
	OnChainStatus       field.Int32   // 上链状态: 1-待上链, 2-上链中, 3-已上链, 4-上链失败
	OnChainAt           field.Time    // 上链时间
	PdfURL              field.String  // PDF文件URL
	PdfHash             field.String  // PDF文件哈希
	PdfSignedBy         field.String  // PDF签名人ID
	PdfSignedAt         field.Time    // PDF签名时间
	SignedBy            field.String  // 证书签发人ID
	IssuedBy            field.String  // 操作人ID
	IssueReason         field.String  // 颁发原因
	RevokedAt           field.Time    // 撤销时间
	RevokedBy           field.String  // 撤销人ID
	RevokeReason        field.String  // 撤销原因
	VerificationCount   field.Int64   // 验证次数
	LastVerifiedAt      field.Time    // 最后验证时间
	ExtraData           field.String  // 扩展数据
	CreatedAt           field.Time    // 创建时间
	UpdatedAt           field.Time    // 更新时间
	DeletedAt           field.Field   // 删除时间
	Version             field.Int64   // 版本号

	fieldMap map[string]field.Expr
}

func (c certificate) Table(newTableName string) *certificate {
	c.certificateDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c certificate) As(alias string) *certificate {
	c.certificateDo.DO = *(c.certificateDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *certificate) updateTableName(table string) *certificate {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.CertificateNo = field.NewString(table, "certificate_no")
	c.TypeID = field.NewString(table, "type_id")
	c.UserID = field.NewString(table, "user_id")
	c.OrganizationID = field.NewString(table, "organization_id")
	c.TemplateID = field.NewString(table, "template_id")
	c.StudentNo = field.NewString(table, "student_no")
	c.Name = field.NewString(table, "name")
	c.IDCardNumber = field.NewString(table, "id_card_number")
	c.Gender = field.NewInt32(table, "gender")
	c.Major = field.NewString(table, "major")
	c.MajorCode = field.NewString(table, "major_code")
	c.Degree = field.NewInt32(table, "degree")
	c.DegreeName = field.NewString(table, "degree_name")
	c.EducationLevel = field.NewInt32(table, "education_level")
	c.EducationType = field.NewInt32(table, "education_type")
	c.EnrollmentDate = field.NewTime(table, "enrollment_date")
	c.GraduationDate = field.NewTime(table, "graduation_date")
	c.StudyPeriod = field.NewString(table, "study_period")
	c.SchoolSystem = field.NewString(table, "school_system")
	c.Campus = field.NewString(table, "campus")
	c.Gpa = field.NewFloat64(table, "gpa")
	c.TotalCredits = field.NewFloat64(table, "total_credits")
	c.Status = field.NewInt32(table, "status")
	c.IssueDate = field.NewTime(table, "issue_date")
	c.ValidFromDate = field.NewTime(table, "valid_from_date")
	c.ValidUntilDate = field.NewTime(table, "valid_until_date")
	c.BlockchainTxHash = field.NewString(table, "blockchain_tx_hash")
	c.BlockchainCertHash = field.NewString(table, "blockchain_cert_hash")
	c.BlockchainBlockNo = field.NewInt64(table, "blockchain_block_no")
	c.BlockchainTimestamp = field.NewTime(table, "blockchain_timestamp")
	c.OnChainStatus = field.NewInt32(table, "on_chain_status")
	c.OnChainAt = field.NewTime(table, "on_chain_at")
	c.PdfURL = field.NewString(table, "pdf_url")
	c.PdfHash = field.NewString(table, "pdf_hash")
	c.PdfSignedBy = field.NewString(table, "pdf_signed_by")
	c.PdfSignedAt = field.NewTime(table, "pdf_signed_at")
	c.SignedBy = field.NewString(table, "signed_by")
	c.IssuedBy = field.NewString(table, "issued_by")
	c.IssueReason = field.NewString(table, "issue_reason")
	c.RevokedAt = field.NewTime(table, "revoked_at")
	c.RevokedBy = field.NewString(table, "revoked_by")
	c.RevokeReason = field.NewString(table, "revoke_reason")
	c.VerificationCount = field.NewInt64(table, "verification_count")
	c.LastVerifiedAt = field.NewTime(table, "last_verified_at")
	c.ExtraData = field.NewString(table, "extra_data")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.Version = field.NewInt64(table, "version")

	c.fillFieldMap()

	return c
}

func (c *certificate) WithContext(ctx context.Context) ICertificateDo {
	return c.certificateDo.WithContext(ctx)
}

func (c certificate) TableName() string { return c.certificateDo.TableName() }

func (c certificate) Alias() string { return c.certificateDo.Alias() }

func (c certificate) Columns(cols ...field.Expr) gen.Columns { return c.certificateDo.Columns(cols...) }

func (c *certificate) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *certificate) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 50)
	c.fieldMap["id"] = c.ID
	c.fieldMap["certificate_no"] = c.CertificateNo
	c.fieldMap["type_id"] = c.TypeID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["organization_id"] = c.OrganizationID
	c.fieldMap["template_id"] = c.TemplateID
	c.fieldMap["student_no"] = c.StudentNo
	c.fieldMap["name"] = c.Name
	c.fieldMap["id_card_number"] = c.IDCardNumber
	c.fieldMap["gender"] = c.Gender
	c.fieldMap["major"] = c.Major
	c.fieldMap["major_code"] = c.MajorCode
	c.fieldMap["degree"] = c.Degree
	c.fieldMap["degree_name"] = c.DegreeName
	c.fieldMap["education_level"] = c.EducationLevel
	c.fieldMap["education_type"] = c.EducationType
	c.fieldMap["enrollment_date"] = c.EnrollmentDate
	c.fieldMap["graduation_date"] = c.GraduationDate
	c.fieldMap["study_period"] = c.StudyPeriod
	c.fieldMap["school_system"] = c.SchoolSystem
	c.fieldMap["campus"] = c.Campus
	c.fieldMap["gpa"] = c.Gpa
	c.fieldMap["total_credits"] = c.TotalCredits
	c.fieldMap["status"] = c.Status
	c.fieldMap["issue_date"] = c.IssueDate
	c.fieldMap["valid_from_date"] = c.ValidFromDate
	c.fieldMap["valid_until_date"] = c.ValidUntilDate
	c.fieldMap["blockchain_tx_hash"] = c.BlockchainTxHash
	c.fieldMap["blockchain_cert_hash"] = c.BlockchainCertHash
	c.fieldMap["blockchain_block_no"] = c.BlockchainBlockNo
	c.fieldMap["blockchain_timestamp"] = c.BlockchainTimestamp
	c.fieldMap["on_chain_status"] = c.OnChainStatus
	c.fieldMap["on_chain_at"] = c.OnChainAt
	c.fieldMap["pdf_url"] = c.PdfURL
	c.fieldMap["pdf_hash"] = c.PdfHash
	c.fieldMap["pdf_signed_by"] = c.PdfSignedBy
	c.fieldMap["pdf_signed_at"] = c.PdfSignedAt
	c.fieldMap["signed_by"] = c.SignedBy
	c.fieldMap["issued_by"] = c.IssuedBy
	c.fieldMap["issue_reason"] = c.IssueReason
	c.fieldMap["revoked_at"] = c.RevokedAt
	c.fieldMap["revoked_by"] = c.RevokedBy
	c.fieldMap["revoke_reason"] = c.RevokeReason
	c.fieldMap["verification_count"] = c.VerificationCount
	c.fieldMap["last_verified_at"] = c.LastVerifiedAt
	c.fieldMap["extra_data"] = c.ExtraData
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["version"] = c.Version
}

func (c certificate) clone(db *gorm.DB) certificate {
	c.certificateDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c certificate) replaceDB(db *gorm.DB) certificate {
	c.certificateDo.ReplaceDB(db)
	return c
}

type certificateDo struct{ gen.DO }

type ICertificateDo interface {
	gen.SubQuery
	Debug() ICertificateDo
	WithContext(ctx context.Context) ICertificateDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICertificateDo
	WriteDB() ICertificateDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICertificateDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICertificateDo
	Not(conds ...gen.Condition) ICertificateDo
	Or(conds ...gen.Condition) ICertificateDo
	Select(conds ...field.Expr) ICertificateDo
	Where(conds ...gen.Condition) ICertificateDo
	Order(conds ...field.Expr) ICertificateDo
	Distinct(cols ...field.Expr) ICertificateDo
	Omit(cols ...field.Expr) ICertificateDo
	Join(table schema.Tabler, on ...field.Expr) ICertificateDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICertificateDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICertificateDo
	Group(cols ...field.Expr) ICertificateDo
	Having(conds ...gen.Condition) ICertificateDo
	Limit(limit int) ICertificateDo
	Offset(offset int) ICertificateDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICertificateDo
	Unscoped() ICertificateDo
	Create(values ...*model.Certificate) error
	CreateInBatches(values []*model.Certificate, batchSize int) error
	Save(values ...*model.Certificate) error
	First() (*model.Certificate, error)
	Take() (*model.Certificate, error)
	Last() (*model.Certificate, error)
	Find() ([]*model.Certificate, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Certificate, err error)
	FindInBatches(result *[]*model.Certificate, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Certificate) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICertificateDo
	Assign(attrs ...field.AssignExpr) ICertificateDo
	Joins(fields ...field.RelationField) ICertificateDo
	Preload(fields ...field.RelationField) ICertificateDo
	FirstOrInit() (*model.Certificate, error)
	FirstOrCreate() (*model.Certificate, error)
	FindByPage(offset int, limit int) (result []*model.Certificate, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICertificateDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c certificateDo) Debug() ICertificateDo {
	return c.withDO(c.DO.Debug())
}

func (c certificateDo) WithContext(ctx context.Context) ICertificateDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c certificateDo) ReadDB() ICertificateDo {
	return c.Clauses(dbresolver.Read)
}

func (c certificateDo) WriteDB() ICertificateDo {
	return c.Clauses(dbresolver.Write)
}

func (c certificateDo) Session(config *gorm.Session) ICertificateDo {
	return c.withDO(c.DO.Session(config))
}

func (c certificateDo) Clauses(conds ...clause.Expression) ICertificateDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c certificateDo) Returning(value interface{}, columns ...string) ICertificateDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c certificateDo) Not(conds ...gen.Condition) ICertificateDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c certificateDo) Or(conds ...gen.Condition) ICertificateDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c certificateDo) Select(conds ...field.Expr) ICertificateDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c certificateDo) Where(conds ...gen.Condition) ICertificateDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c certificateDo) Order(conds ...field.Expr) ICertificateDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c certificateDo) Distinct(cols ...field.Expr) ICertificateDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c certificateDo) Omit(cols ...field.Expr) ICertificateDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c certificateDo) Join(table schema.Tabler, on ...field.Expr) ICertificateDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c certificateDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICertificateDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c certificateDo) RightJoin(table schema.Tabler, on ...field.Expr) ICertificateDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c certificateDo) Group(cols ...field.Expr) ICertificateDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c certificateDo) Having(conds ...gen.Condition) ICertificateDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c certificateDo) Limit(limit int) ICertificateDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c certificateDo) Offset(offset int) ICertificateDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c certificateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICertificateDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c certificateDo) Unscoped() ICertificateDo {
	return c.withDO(c.DO.Unscoped())
}

func (c certificateDo) Create(values ...*model.Certificate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c certificateDo) CreateInBatches(values []*model.Certificate, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c certificateDo) Save(values ...*model.Certificate) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c certificateDo) First() (*model.Certificate, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) Take() (*model.Certificate, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) Last() (*model.Certificate, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) Find() ([]*model.Certificate, error) {
	result, err := c.DO.Find()
	return result.([]*model.Certificate), err
}

func (c certificateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Certificate, err error) {
	buf := make([]*model.Certificate, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c certificateDo) FindInBatches(result *[]*model.Certificate, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c certificateDo) Attrs(attrs ...field.AssignExpr) ICertificateDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c certificateDo) Assign(attrs ...field.AssignExpr) ICertificateDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c certificateDo) Joins(fields ...field.RelationField) ICertificateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c certificateDo) Preload(fields ...field.RelationField) ICertificateDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c certificateDo) FirstOrInit() (*model.Certificate, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) FirstOrCreate() (*model.Certificate, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Certificate), nil
	}
}

func (c certificateDo) FindByPage(offset int, limit int) (result []*model.Certificate, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c certificateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c certificateDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c certificateDo) Delete(models ...*model.Certificate) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *certificateDo) withDO(do gen.Dao) *certificateDo {
	c.DO = *do.(*gen.DO)
	return c
}
