// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	AuditLog              *auditLog
	BlockchainNetwork     *blockchainNetwork
	BlockchainTransaction *blockchainTransaction
	Certificate           *certificate
	CertificateBatch      *certificateBatch
	CertificateTemplate   *certificateTemplate
	CertificateType       *certificateType
	Department            *department
	Dictionary            *dictionary
	FileRecord            *fileRecord
	JobQueue              *jobQueue
	Organization          *organization
	OrganizationUser      *organizationUser
	Permission            *permission
	RefreshToken          *refreshToken
	Role                  *role
	RolePermission        *rolePermission
	SmartContract         *smartContract
	SystemConfig          *systemConfig
	User                  *user
	UserRole              *userRole
	Verification          *verification
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AuditLog = &Q.AuditLog
	BlockchainNetwork = &Q.BlockchainNetwork
	BlockchainTransaction = &Q.BlockchainTransaction
	Certificate = &Q.Certificate
	CertificateBatch = &Q.CertificateBatch
	CertificateTemplate = &Q.CertificateTemplate
	CertificateType = &Q.CertificateType
	Department = &Q.Department
	Dictionary = &Q.Dictionary
	FileRecord = &Q.FileRecord
	JobQueue = &Q.JobQueue
	Organization = &Q.Organization
	OrganizationUser = &Q.OrganizationUser
	Permission = &Q.Permission
	RefreshToken = &Q.RefreshToken
	Role = &Q.Role
	RolePermission = &Q.RolePermission
	SmartContract = &Q.SmartContract
	SystemConfig = &Q.SystemConfig
	User = &Q.User
	UserRole = &Q.UserRole
	Verification = &Q.Verification
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		AuditLog:              newAuditLog(db, opts...),
		BlockchainNetwork:     newBlockchainNetwork(db, opts...),
		BlockchainTransaction: newBlockchainTransaction(db, opts...),
		Certificate:           newCertificate(db, opts...),
		CertificateBatch:      newCertificateBatch(db, opts...),
		CertificateTemplate:   newCertificateTemplate(db, opts...),
		CertificateType:       newCertificateType(db, opts...),
		Department:            newDepartment(db, opts...),
		Dictionary:            newDictionary(db, opts...),
		FileRecord:            newFileRecord(db, opts...),
		JobQueue:              newJobQueue(db, opts...),
		Organization:          newOrganization(db, opts...),
		OrganizationUser:      newOrganizationUser(db, opts...),
		Permission:            newPermission(db, opts...),
		RefreshToken:          newRefreshToken(db, opts...),
		Role:                  newRole(db, opts...),
		RolePermission:        newRolePermission(db, opts...),
		SmartContract:         newSmartContract(db, opts...),
		SystemConfig:          newSystemConfig(db, opts...),
		User:                  newUser(db, opts...),
		UserRole:              newUserRole(db, opts...),
		Verification:          newVerification(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AuditLog              auditLog
	BlockchainNetwork     blockchainNetwork
	BlockchainTransaction blockchainTransaction
	Certificate           certificate
	CertificateBatch      certificateBatch
	CertificateTemplate   certificateTemplate
	CertificateType       certificateType
	Department            department
	Dictionary            dictionary
	FileRecord            fileRecord
	JobQueue              jobQueue
	Organization          organization
	OrganizationUser      organizationUser
	Permission            permission
	RefreshToken          refreshToken
	Role                  role
	RolePermission        rolePermission
	SmartContract         smartContract
	SystemConfig          systemConfig
	User                  user
	UserRole              userRole
	Verification          verification
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		AuditLog:              q.AuditLog.clone(db),
		BlockchainNetwork:     q.BlockchainNetwork.clone(db),
		BlockchainTransaction: q.BlockchainTransaction.clone(db),
		Certificate:           q.Certificate.clone(db),
		CertificateBatch:      q.CertificateBatch.clone(db),
		CertificateTemplate:   q.CertificateTemplate.clone(db),
		CertificateType:       q.CertificateType.clone(db),
		Department:            q.Department.clone(db),
		Dictionary:            q.Dictionary.clone(db),
		FileRecord:            q.FileRecord.clone(db),
		JobQueue:              q.JobQueue.clone(db),
		Organization:          q.Organization.clone(db),
		OrganizationUser:      q.OrganizationUser.clone(db),
		Permission:            q.Permission.clone(db),
		RefreshToken:          q.RefreshToken.clone(db),
		Role:                  q.Role.clone(db),
		RolePermission:        q.RolePermission.clone(db),
		SmartContract:         q.SmartContract.clone(db),
		SystemConfig:          q.SystemConfig.clone(db),
		User:                  q.User.clone(db),
		UserRole:              q.UserRole.clone(db),
		Verification:          q.Verification.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		AuditLog:              q.AuditLog.replaceDB(db),
		BlockchainNetwork:     q.BlockchainNetwork.replaceDB(db),
		BlockchainTransaction: q.BlockchainTransaction.replaceDB(db),
		Certificate:           q.Certificate.replaceDB(db),
		CertificateBatch:      q.CertificateBatch.replaceDB(db),
		CertificateTemplate:   q.CertificateTemplate.replaceDB(db),
		CertificateType:       q.CertificateType.replaceDB(db),
		Department:            q.Department.replaceDB(db),
		Dictionary:            q.Dictionary.replaceDB(db),
		FileRecord:            q.FileRecord.replaceDB(db),
		JobQueue:              q.JobQueue.replaceDB(db),
		Organization:          q.Organization.replaceDB(db),
		OrganizationUser:      q.OrganizationUser.replaceDB(db),
		Permission:            q.Permission.replaceDB(db),
		RefreshToken:          q.RefreshToken.replaceDB(db),
		Role:                  q.Role.replaceDB(db),
		RolePermission:        q.RolePermission.replaceDB(db),
		SmartContract:         q.SmartContract.replaceDB(db),
		SystemConfig:          q.SystemConfig.replaceDB(db),
		User:                  q.User.replaceDB(db),
		UserRole:              q.UserRole.replaceDB(db),
		Verification:          q.Verification.replaceDB(db),
	}
}

type queryCtx struct {
	AuditLog              IAuditLogDo
	BlockchainNetwork     IBlockchainNetworkDo
	BlockchainTransaction IBlockchainTransactionDo
	Certificate           ICertificateDo
	CertificateBatch      ICertificateBatchDo
	CertificateTemplate   ICertificateTemplateDo
	CertificateType       ICertificateTypeDo
	Department            IDepartmentDo
	Dictionary            IDictionaryDo
	FileRecord            IFileRecordDo
	JobQueue              IJobQueueDo
	Organization          IOrganizationDo
	OrganizationUser      IOrganizationUserDo
	Permission            IPermissionDo
	RefreshToken          IRefreshTokenDo
	Role                  IRoleDo
	RolePermission        IRolePermissionDo
	SmartContract         ISmartContractDo
	SystemConfig          ISystemConfigDo
	User                  IUserDo
	UserRole              IUserRoleDo
	Verification          IVerificationDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AuditLog:              q.AuditLog.WithContext(ctx),
		BlockchainNetwork:     q.BlockchainNetwork.WithContext(ctx),
		BlockchainTransaction: q.BlockchainTransaction.WithContext(ctx),
		Certificate:           q.Certificate.WithContext(ctx),
		CertificateBatch:      q.CertificateBatch.WithContext(ctx),
		CertificateTemplate:   q.CertificateTemplate.WithContext(ctx),
		CertificateType:       q.CertificateType.WithContext(ctx),
		Department:            q.Department.WithContext(ctx),
		Dictionary:            q.Dictionary.WithContext(ctx),
		FileRecord:            q.FileRecord.WithContext(ctx),
		JobQueue:              q.JobQueue.WithContext(ctx),
		Organization:          q.Organization.WithContext(ctx),
		OrganizationUser:      q.OrganizationUser.WithContext(ctx),
		Permission:            q.Permission.WithContext(ctx),
		RefreshToken:          q.RefreshToken.WithContext(ctx),
		Role:                  q.Role.WithContext(ctx),
		RolePermission:        q.RolePermission.WithContext(ctx),
		SmartContract:         q.SmartContract.WithContext(ctx),
		SystemConfig:          q.SystemConfig.WithContext(ctx),
		User:                  q.User.WithContext(ctx),
		UserRole:              q.UserRole.WithContext(ctx),
		Verification:          q.Verification.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
