// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yz626/edu-chain/internal/data/repository/model"
)

func newJobQueue(db *gorm.DB, opts ...gen.DOOption) jobQueue {
	_jobQueue := jobQueue{}

	_jobQueue.jobQueueDo.UseDB(db, opts...)
	_jobQueue.jobQueueDo.UseModel(&model.JobQueue{})

	tableName := _jobQueue.jobQueueDo.TableName()
	_jobQueue.ALL = field.NewAsterisk(tableName)
	_jobQueue.ID = field.NewString(tableName, "id")
	_jobQueue.JobType = field.NewString(tableName, "job_type")
	_jobQueue.JobName = field.NewString(tableName, "job_name")
	_jobQueue.Payload = field.NewString(tableName, "payload")
	_jobQueue.Priority = field.NewInt32(tableName, "priority")
	_jobQueue.Status = field.NewInt32(tableName, "status")
	_jobQueue.RetryCount = field.NewInt32(tableName, "retry_count")
	_jobQueue.MaxRetryCount = field.NewInt32(tableName, "max_retry_count")
	_jobQueue.NextRetryAt = field.NewTime(tableName, "next_retry_at")
	_jobQueue.StartedAt = field.NewTime(tableName, "started_at")
	_jobQueue.CompletedAt = field.NewTime(tableName, "completed_at")
	_jobQueue.ProgressPercent = field.NewInt32(tableName, "progress_percent")
	_jobQueue.ResultData = field.NewString(tableName, "result_data")
	_jobQueue.ErrorMessage = field.NewString(tableName, "error_message")
	_jobQueue.ScheduledAt = field.NewTime(tableName, "scheduled_at")
	_jobQueue.CreatedAt = field.NewTime(tableName, "created_at")
	_jobQueue.UpdatedAt = field.NewTime(tableName, "updated_at")

	_jobQueue.fillFieldMap()

	return _jobQueue
}

type jobQueue struct {
	jobQueueDo jobQueueDo

	ALL             field.Asterisk
	ID              field.String // 任务ID (UUID)
	JobType         field.String // 任务类型
	JobName         field.String // 任务名称
	Payload         field.String // 任务数据 (JSON)
	Priority        field.Int32  // 优先级: 1-最高, 10-最低
	Status          field.Int32  // 任务状态: 1-等待, 2-执行中, 3-成功, 4-失败, 5-已取消, 6-已重试
	RetryCount      field.Int32  // 已重试次数
	MaxRetryCount   field.Int32  // 最大重试次数
	NextRetryAt     field.Time   // 下次重试时间
	StartedAt       field.Time   // 开始执行时间
	CompletedAt     field.Time   // 完成时间
	ProgressPercent field.Int32  // 进度百分比 (0-100)
	ResultData      field.String // 执行结果
	ErrorMessage    field.String // 错误信息
	ScheduledAt     field.Time   // 计划执行时间
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (j jobQueue) Table(newTableName string) *jobQueue {
	j.jobQueueDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobQueue) As(alias string) *jobQueue {
	j.jobQueueDo.DO = *(j.jobQueueDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobQueue) updateTableName(table string) *jobQueue {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewString(table, "id")
	j.JobType = field.NewString(table, "job_type")
	j.JobName = field.NewString(table, "job_name")
	j.Payload = field.NewString(table, "payload")
	j.Priority = field.NewInt32(table, "priority")
	j.Status = field.NewInt32(table, "status")
	j.RetryCount = field.NewInt32(table, "retry_count")
	j.MaxRetryCount = field.NewInt32(table, "max_retry_count")
	j.NextRetryAt = field.NewTime(table, "next_retry_at")
	j.StartedAt = field.NewTime(table, "started_at")
	j.CompletedAt = field.NewTime(table, "completed_at")
	j.ProgressPercent = field.NewInt32(table, "progress_percent")
	j.ResultData = field.NewString(table, "result_data")
	j.ErrorMessage = field.NewString(table, "error_message")
	j.ScheduledAt = field.NewTime(table, "scheduled_at")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")

	j.fillFieldMap()

	return j
}

func (j *jobQueue) WithContext(ctx context.Context) IJobQueueDo { return j.jobQueueDo.WithContext(ctx) }

func (j jobQueue) TableName() string { return j.jobQueueDo.TableName() }

func (j jobQueue) Alias() string { return j.jobQueueDo.Alias() }

func (j jobQueue) Columns(cols ...field.Expr) gen.Columns { return j.jobQueueDo.Columns(cols...) }

func (j *jobQueue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobQueue) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 17)
	j.fieldMap["id"] = j.ID
	j.fieldMap["job_type"] = j.JobType
	j.fieldMap["job_name"] = j.JobName
	j.fieldMap["payload"] = j.Payload
	j.fieldMap["priority"] = j.Priority
	j.fieldMap["status"] = j.Status
	j.fieldMap["retry_count"] = j.RetryCount
	j.fieldMap["max_retry_count"] = j.MaxRetryCount
	j.fieldMap["next_retry_at"] = j.NextRetryAt
	j.fieldMap["started_at"] = j.StartedAt
	j.fieldMap["completed_at"] = j.CompletedAt
	j.fieldMap["progress_percent"] = j.ProgressPercent
	j.fieldMap["result_data"] = j.ResultData
	j.fieldMap["error_message"] = j.ErrorMessage
	j.fieldMap["scheduled_at"] = j.ScheduledAt
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
}

func (j jobQueue) clone(db *gorm.DB) jobQueue {
	j.jobQueueDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobQueue) replaceDB(db *gorm.DB) jobQueue {
	j.jobQueueDo.ReplaceDB(db)
	return j
}

type jobQueueDo struct{ gen.DO }

type IJobQueueDo interface {
	gen.SubQuery
	Debug() IJobQueueDo
	WithContext(ctx context.Context) IJobQueueDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobQueueDo
	WriteDB() IJobQueueDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobQueueDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobQueueDo
	Not(conds ...gen.Condition) IJobQueueDo
	Or(conds ...gen.Condition) IJobQueueDo
	Select(conds ...field.Expr) IJobQueueDo
	Where(conds ...gen.Condition) IJobQueueDo
	Order(conds ...field.Expr) IJobQueueDo
	Distinct(cols ...field.Expr) IJobQueueDo
	Omit(cols ...field.Expr) IJobQueueDo
	Join(table schema.Tabler, on ...field.Expr) IJobQueueDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobQueueDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobQueueDo
	Group(cols ...field.Expr) IJobQueueDo
	Having(conds ...gen.Condition) IJobQueueDo
	Limit(limit int) IJobQueueDo
	Offset(offset int) IJobQueueDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobQueueDo
	Unscoped() IJobQueueDo
	Create(values ...*model.JobQueue) error
	CreateInBatches(values []*model.JobQueue, batchSize int) error
	Save(values ...*model.JobQueue) error
	First() (*model.JobQueue, error)
	Take() (*model.JobQueue, error)
	Last() (*model.JobQueue, error)
	Find() ([]*model.JobQueue, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobQueue, err error)
	FindInBatches(result *[]*model.JobQueue, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.JobQueue) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobQueueDo
	Assign(attrs ...field.AssignExpr) IJobQueueDo
	Joins(fields ...field.RelationField) IJobQueueDo
	Preload(fields ...field.RelationField) IJobQueueDo
	FirstOrInit() (*model.JobQueue, error)
	FirstOrCreate() (*model.JobQueue, error)
	FindByPage(offset int, limit int) (result []*model.JobQueue, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobQueueDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobQueueDo) Debug() IJobQueueDo {
	return j.withDO(j.DO.Debug())
}

func (j jobQueueDo) WithContext(ctx context.Context) IJobQueueDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobQueueDo) ReadDB() IJobQueueDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobQueueDo) WriteDB() IJobQueueDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobQueueDo) Session(config *gorm.Session) IJobQueueDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobQueueDo) Clauses(conds ...clause.Expression) IJobQueueDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobQueueDo) Returning(value interface{}, columns ...string) IJobQueueDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobQueueDo) Not(conds ...gen.Condition) IJobQueueDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobQueueDo) Or(conds ...gen.Condition) IJobQueueDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobQueueDo) Select(conds ...field.Expr) IJobQueueDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobQueueDo) Where(conds ...gen.Condition) IJobQueueDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobQueueDo) Order(conds ...field.Expr) IJobQueueDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobQueueDo) Distinct(cols ...field.Expr) IJobQueueDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobQueueDo) Omit(cols ...field.Expr) IJobQueueDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobQueueDo) Join(table schema.Tabler, on ...field.Expr) IJobQueueDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobQueueDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobQueueDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobQueueDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobQueueDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobQueueDo) Group(cols ...field.Expr) IJobQueueDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobQueueDo) Having(conds ...gen.Condition) IJobQueueDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobQueueDo) Limit(limit int) IJobQueueDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobQueueDo) Offset(offset int) IJobQueueDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobQueueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobQueueDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobQueueDo) Unscoped() IJobQueueDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobQueueDo) Create(values ...*model.JobQueue) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobQueueDo) CreateInBatches(values []*model.JobQueue, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobQueueDo) Save(values ...*model.JobQueue) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobQueueDo) First() (*model.JobQueue, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobQueue), nil
	}
}

func (j jobQueueDo) Take() (*model.JobQueue, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobQueue), nil
	}
}

func (j jobQueueDo) Last() (*model.JobQueue, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobQueue), nil
	}
}

func (j jobQueueDo) Find() ([]*model.JobQueue, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobQueue), err
}

func (j jobQueueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobQueue, err error) {
	buf := make([]*model.JobQueue, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobQueueDo) FindInBatches(result *[]*model.JobQueue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobQueueDo) Attrs(attrs ...field.AssignExpr) IJobQueueDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobQueueDo) Assign(attrs ...field.AssignExpr) IJobQueueDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobQueueDo) Joins(fields ...field.RelationField) IJobQueueDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobQueueDo) Preload(fields ...field.RelationField) IJobQueueDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobQueueDo) FirstOrInit() (*model.JobQueue, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobQueue), nil
	}
}

func (j jobQueueDo) FirstOrCreate() (*model.JobQueue, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobQueue), nil
	}
}

func (j jobQueueDo) FindByPage(offset int, limit int) (result []*model.JobQueue, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobQueueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobQueueDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobQueueDo) Delete(models ...*model.JobQueue) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobQueueDo) withDO(do gen.Dao) *jobQueueDo {
	j.DO = *do.(*gen.DO)
	return j
}
