// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yz626/edu-chain/internal/data/repository/model"
)

func newSmartContract(db *gorm.DB, opts ...gen.DOOption) smartContract {
	_smartContract := smartContract{}

	_smartContract.smartContractDo.UseDB(db, opts...)
	_smartContract.smartContractDo.UseModel(&model.SmartContract{})

	tableName := _smartContract.smartContractDo.TableName()
	_smartContract.ALL = field.NewAsterisk(tableName)
	_smartContract.ID = field.NewString(tableName, "id")
	_smartContract.Name = field.NewString(tableName, "name")
	_smartContract.Code = field.NewString(tableName, "code")
	_smartContract.NetworkID = field.NewString(tableName, "network_id")
	_smartContract.ContractAddress = field.NewString(tableName, "contract_address")
	_smartContract.Abi = field.NewString(tableName, "abi")
	_smartContract.Bytecode = field.NewString(tableName, "bytecode")
	_smartContract.Version = field.NewString(tableName, "version")
	_smartContract.DeployerAddress = field.NewString(tableName, "deployer_address")
	_smartContract.DeployedAt = field.NewTime(tableName, "deployed_at")
	_smartContract.Status = field.NewInt32(tableName, "status")
	_smartContract.IsVerified = field.NewBool(tableName, "is_verified")
	_smartContract.VerifiedAt = field.NewTime(tableName, "verified_at")
	_smartContract.ExtraData = field.NewString(tableName, "extra_data")
	_smartContract.CreatedAt = field.NewTime(tableName, "created_at")
	_smartContract.UpdatedAt = field.NewTime(tableName, "updated_at")

	_smartContract.fillFieldMap()

	return _smartContract
}

type smartContract struct {
	smartContractDo smartContractDo

	ALL             field.Asterisk
	ID              field.String // 合约ID (UUID)
	Name            field.String // 合约名称
	Code            field.String // 合约代码 (唯一标识)
	NetworkID       field.String // 部署网络ID
	ContractAddress field.String // 合约地址
	Abi             field.String // ABI接口定义
	Bytecode        field.String // 字节码
	Version         field.String // 合约版本
	DeployerAddress field.String // 部署者地址
	DeployedAt      field.Time   // 部署时间
	Status          field.Int32  // 状态: 1-正常, 2-停用, 3-已废弃
	IsVerified      field.Bool   // 是否已验证源码
	VerifiedAt      field.Time   // 验证时间
	ExtraData       field.String // 扩展数据
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s smartContract) Table(newTableName string) *smartContract {
	s.smartContractDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s smartContract) As(alias string) *smartContract {
	s.smartContractDo.DO = *(s.smartContractDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *smartContract) updateTableName(table string) *smartContract {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.NetworkID = field.NewString(table, "network_id")
	s.ContractAddress = field.NewString(table, "contract_address")
	s.Abi = field.NewString(table, "abi")
	s.Bytecode = field.NewString(table, "bytecode")
	s.Version = field.NewString(table, "version")
	s.DeployerAddress = field.NewString(table, "deployer_address")
	s.DeployedAt = field.NewTime(table, "deployed_at")
	s.Status = field.NewInt32(table, "status")
	s.IsVerified = field.NewBool(table, "is_verified")
	s.VerifiedAt = field.NewTime(table, "verified_at")
	s.ExtraData = field.NewString(table, "extra_data")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *smartContract) WithContext(ctx context.Context) ISmartContractDo {
	return s.smartContractDo.WithContext(ctx)
}

func (s smartContract) TableName() string { return s.smartContractDo.TableName() }

func (s smartContract) Alias() string { return s.smartContractDo.Alias() }

func (s smartContract) Columns(cols ...field.Expr) gen.Columns {
	return s.smartContractDo.Columns(cols...)
}

func (s *smartContract) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *smartContract) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["network_id"] = s.NetworkID
	s.fieldMap["contract_address"] = s.ContractAddress
	s.fieldMap["abi"] = s.Abi
	s.fieldMap["bytecode"] = s.Bytecode
	s.fieldMap["version"] = s.Version
	s.fieldMap["deployer_address"] = s.DeployerAddress
	s.fieldMap["deployed_at"] = s.DeployedAt
	s.fieldMap["status"] = s.Status
	s.fieldMap["is_verified"] = s.IsVerified
	s.fieldMap["verified_at"] = s.VerifiedAt
	s.fieldMap["extra_data"] = s.ExtraData
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s smartContract) clone(db *gorm.DB) smartContract {
	s.smartContractDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s smartContract) replaceDB(db *gorm.DB) smartContract {
	s.smartContractDo.ReplaceDB(db)
	return s
}

type smartContractDo struct{ gen.DO }

type ISmartContractDo interface {
	gen.SubQuery
	Debug() ISmartContractDo
	WithContext(ctx context.Context) ISmartContractDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISmartContractDo
	WriteDB() ISmartContractDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISmartContractDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISmartContractDo
	Not(conds ...gen.Condition) ISmartContractDo
	Or(conds ...gen.Condition) ISmartContractDo
	Select(conds ...field.Expr) ISmartContractDo
	Where(conds ...gen.Condition) ISmartContractDo
	Order(conds ...field.Expr) ISmartContractDo
	Distinct(cols ...field.Expr) ISmartContractDo
	Omit(cols ...field.Expr) ISmartContractDo
	Join(table schema.Tabler, on ...field.Expr) ISmartContractDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISmartContractDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISmartContractDo
	Group(cols ...field.Expr) ISmartContractDo
	Having(conds ...gen.Condition) ISmartContractDo
	Limit(limit int) ISmartContractDo
	Offset(offset int) ISmartContractDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISmartContractDo
	Unscoped() ISmartContractDo
	Create(values ...*model.SmartContract) error
	CreateInBatches(values []*model.SmartContract, batchSize int) error
	Save(values ...*model.SmartContract) error
	First() (*model.SmartContract, error)
	Take() (*model.SmartContract, error)
	Last() (*model.SmartContract, error)
	Find() ([]*model.SmartContract, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SmartContract, err error)
	FindInBatches(result *[]*model.SmartContract, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SmartContract) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISmartContractDo
	Assign(attrs ...field.AssignExpr) ISmartContractDo
	Joins(fields ...field.RelationField) ISmartContractDo
	Preload(fields ...field.RelationField) ISmartContractDo
	FirstOrInit() (*model.SmartContract, error)
	FirstOrCreate() (*model.SmartContract, error)
	FindByPage(offset int, limit int) (result []*model.SmartContract, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISmartContractDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s smartContractDo) Debug() ISmartContractDo {
	return s.withDO(s.DO.Debug())
}

func (s smartContractDo) WithContext(ctx context.Context) ISmartContractDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s smartContractDo) ReadDB() ISmartContractDo {
	return s.Clauses(dbresolver.Read)
}

func (s smartContractDo) WriteDB() ISmartContractDo {
	return s.Clauses(dbresolver.Write)
}

func (s smartContractDo) Session(config *gorm.Session) ISmartContractDo {
	return s.withDO(s.DO.Session(config))
}

func (s smartContractDo) Clauses(conds ...clause.Expression) ISmartContractDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s smartContractDo) Returning(value interface{}, columns ...string) ISmartContractDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s smartContractDo) Not(conds ...gen.Condition) ISmartContractDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s smartContractDo) Or(conds ...gen.Condition) ISmartContractDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s smartContractDo) Select(conds ...field.Expr) ISmartContractDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s smartContractDo) Where(conds ...gen.Condition) ISmartContractDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s smartContractDo) Order(conds ...field.Expr) ISmartContractDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s smartContractDo) Distinct(cols ...field.Expr) ISmartContractDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s smartContractDo) Omit(cols ...field.Expr) ISmartContractDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s smartContractDo) Join(table schema.Tabler, on ...field.Expr) ISmartContractDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s smartContractDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISmartContractDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s smartContractDo) RightJoin(table schema.Tabler, on ...field.Expr) ISmartContractDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s smartContractDo) Group(cols ...field.Expr) ISmartContractDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s smartContractDo) Having(conds ...gen.Condition) ISmartContractDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s smartContractDo) Limit(limit int) ISmartContractDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s smartContractDo) Offset(offset int) ISmartContractDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s smartContractDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISmartContractDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s smartContractDo) Unscoped() ISmartContractDo {
	return s.withDO(s.DO.Unscoped())
}

func (s smartContractDo) Create(values ...*model.SmartContract) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s smartContractDo) CreateInBatches(values []*model.SmartContract, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s smartContractDo) Save(values ...*model.SmartContract) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s smartContractDo) First() (*model.SmartContract, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmartContract), nil
	}
}

func (s smartContractDo) Take() (*model.SmartContract, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmartContract), nil
	}
}

func (s smartContractDo) Last() (*model.SmartContract, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmartContract), nil
	}
}

func (s smartContractDo) Find() ([]*model.SmartContract, error) {
	result, err := s.DO.Find()
	return result.([]*model.SmartContract), err
}

func (s smartContractDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SmartContract, err error) {
	buf := make([]*model.SmartContract, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s smartContractDo) FindInBatches(result *[]*model.SmartContract, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s smartContractDo) Attrs(attrs ...field.AssignExpr) ISmartContractDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s smartContractDo) Assign(attrs ...field.AssignExpr) ISmartContractDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s smartContractDo) Joins(fields ...field.RelationField) ISmartContractDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s smartContractDo) Preload(fields ...field.RelationField) ISmartContractDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s smartContractDo) FirstOrInit() (*model.SmartContract, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmartContract), nil
	}
}

func (s smartContractDo) FirstOrCreate() (*model.SmartContract, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SmartContract), nil
	}
}

func (s smartContractDo) FindByPage(offset int, limit int) (result []*model.SmartContract, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s smartContractDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s smartContractDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s smartContractDo) Delete(models ...*model.SmartContract) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *smartContractDo) withDO(do gen.Dao) *smartContractDo {
	s.DO = *do.(*gen.DO)
	return s
}
