// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/yz626/edu-chain/internal/data/repository/model"
)

func newVerification(db *gorm.DB, opts ...gen.DOOption) verification {
	_verification := verification{}

	_verification.verificationDo.UseDB(db, opts...)
	_verification.verificationDo.UseModel(&model.Verification{})

	tableName := _verification.verificationDo.TableName()
	_verification.ALL = field.NewAsterisk(tableName)
	_verification.ID = field.NewString(tableName, "id")
	_verification.VerificationNo = field.NewString(tableName, "verification_no")
	_verification.CertificateID = field.NewString(tableName, "certificate_id")
	_verification.UserID = field.NewString(tableName, "user_id")
	_verification.VerifierID = field.NewString(tableName, "verifier_id")
	_verification.VerifierOrgID = field.NewString(tableName, "verifier_org_id")
	_verification.VerifierOrgName = field.NewString(tableName, "verifier_org_name")
	_verification.VerificationType = field.NewInt32(tableName, "verification_type")
	_verification.Purpose = field.NewString(tableName, "purpose")
	_verification.InputType = field.NewInt32(tableName, "input_type")
	_verification.InputData = field.NewString(tableName, "input_data")
	_verification.Result = field.NewInt32(tableName, "result")
	_verification.ResultDetails = field.NewString(tableName, "result_details")
	_verification.MatchedFields = field.NewString(tableName, "matched_fields")
	_verification.MismatchFields = field.NewString(tableName, "mismatch_fields")
	_verification.BlockchainVerified = field.NewBool(tableName, "blockchain_verified")
	_verification.BlockchainResult = field.NewString(tableName, "blockchain_result")
	_verification.ReportURL = field.NewString(tableName, "report_url")
	_verification.ReportID = field.NewString(tableName, "report_id")
	_verification.RiskLevel = field.NewInt32(tableName, "risk_level")
	_verification.RiskFactors = field.NewString(tableName, "risk_factors")
	_verification.ReviewedBy = field.NewString(tableName, "reviewed_by")
	_verification.ReviewedAt = field.NewTime(tableName, "reviewed_at")
	_verification.ReviewResult = field.NewInt32(tableName, "review_result")
	_verification.ReviewNotes = field.NewString(tableName, "review_notes")
	_verification.IPAddress = field.NewString(tableName, "ip_address")
	_verification.UserAgent = field.NewString(tableName, "user_agent")
	_verification.Location = field.NewString(tableName, "location")
	_verification.Status = field.NewInt32(tableName, "status")
	_verification.ExpiresAt = field.NewTime(tableName, "expires_at")
	_verification.VerifiedAt = field.NewTime(tableName, "verified_at")
	_verification.CreatedAt = field.NewTime(tableName, "created_at")
	_verification.UpdatedAt = field.NewTime(tableName, "updated_at")

	_verification.fillFieldMap()

	return _verification
}

type verification struct {
	verificationDo verificationDo

	ALL                field.Asterisk
	ID                 field.String // 验证记录ID (UUID)
	VerificationNo     field.String // 验证流水号 (唯一)
	CertificateID      field.String // 证书ID
	UserID             field.String // 验证人用户ID
	VerifierID         field.String // 验证操作人ID
	VerifierOrgID      field.String // 验证人所属组织ID
	VerifierOrgName    field.String // 验证人所属组织名称
	VerificationType   field.Int32  // 验证类型: 1-本人查询, 2-机构验证, 3-管理员查询, 4-批量验证
	Purpose            field.String // 验证用途
	InputType          field.Int32  // 输入类型: 1-证书编号, 2-身份证号, 3-姓名+身份证, 4-扫码验证
	InputData          field.String // 输入数据
	Result             field.Int32  // 验证结果: 1-真实, 2-可疑, 3-未匹配, 4-已撤销
	ResultDetails      field.String // 验证结果详情
	MatchedFields      field.String // 匹配的字段列表
	MismatchFields     field.String // 不匹配的字段列表
	BlockchainVerified field.Bool   // 区块链是否已验证
	BlockchainResult   field.String // 区块链验证结果
	ReportURL          field.String // 验证报告URL
	ReportID           field.String // 报告ID
	RiskLevel          field.Int32  // 风险等级: 1-低, 2-中, 3-高, 4-极高, 5-已确认欺诈
	RiskFactors        field.String // 风险因素列表
	ReviewedBy         field.String // 审核人ID
	ReviewedAt         field.Time   // 审核时间
	ReviewResult       field.Int32  // 审核结果
	ReviewNotes        field.String // 审核备注
	IPAddress          field.String // 请求IP地址
	UserAgent          field.String // User-Agent
	Location           field.String // 地理位置
	Status             field.Int32  // 状态: 1-待验证, 2-验证中, 3-已完成, 4-已过期
	ExpiresAt          field.Time   // 过期时间
	VerifiedAt         field.Time   // 验证完成时间
	CreatedAt          field.Time   // 创建时间
	UpdatedAt          field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (v verification) Table(newTableName string) *verification {
	v.verificationDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v verification) As(alias string) *verification {
	v.verificationDo.DO = *(v.verificationDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *verification) updateTableName(table string) *verification {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewString(table, "id")
	v.VerificationNo = field.NewString(table, "verification_no")
	v.CertificateID = field.NewString(table, "certificate_id")
	v.UserID = field.NewString(table, "user_id")
	v.VerifierID = field.NewString(table, "verifier_id")
	v.VerifierOrgID = field.NewString(table, "verifier_org_id")
	v.VerifierOrgName = field.NewString(table, "verifier_org_name")
	v.VerificationType = field.NewInt32(table, "verification_type")
	v.Purpose = field.NewString(table, "purpose")
	v.InputType = field.NewInt32(table, "input_type")
	v.InputData = field.NewString(table, "input_data")
	v.Result = field.NewInt32(table, "result")
	v.ResultDetails = field.NewString(table, "result_details")
	v.MatchedFields = field.NewString(table, "matched_fields")
	v.MismatchFields = field.NewString(table, "mismatch_fields")
	v.BlockchainVerified = field.NewBool(table, "blockchain_verified")
	v.BlockchainResult = field.NewString(table, "blockchain_result")
	v.ReportURL = field.NewString(table, "report_url")
	v.ReportID = field.NewString(table, "report_id")
	v.RiskLevel = field.NewInt32(table, "risk_level")
	v.RiskFactors = field.NewString(table, "risk_factors")
	v.ReviewedBy = field.NewString(table, "reviewed_by")
	v.ReviewedAt = field.NewTime(table, "reviewed_at")
	v.ReviewResult = field.NewInt32(table, "review_result")
	v.ReviewNotes = field.NewString(table, "review_notes")
	v.IPAddress = field.NewString(table, "ip_address")
	v.UserAgent = field.NewString(table, "user_agent")
	v.Location = field.NewString(table, "location")
	v.Status = field.NewInt32(table, "status")
	v.ExpiresAt = field.NewTime(table, "expires_at")
	v.VerifiedAt = field.NewTime(table, "verified_at")
	v.CreatedAt = field.NewTime(table, "created_at")
	v.UpdatedAt = field.NewTime(table, "updated_at")

	v.fillFieldMap()

	return v
}

func (v *verification) WithContext(ctx context.Context) IVerificationDo {
	return v.verificationDo.WithContext(ctx)
}

func (v verification) TableName() string { return v.verificationDo.TableName() }

func (v verification) Alias() string { return v.verificationDo.Alias() }

func (v verification) Columns(cols ...field.Expr) gen.Columns {
	return v.verificationDo.Columns(cols...)
}

func (v *verification) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *verification) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 33)
	v.fieldMap["id"] = v.ID
	v.fieldMap["verification_no"] = v.VerificationNo
	v.fieldMap["certificate_id"] = v.CertificateID
	v.fieldMap["user_id"] = v.UserID
	v.fieldMap["verifier_id"] = v.VerifierID
	v.fieldMap["verifier_org_id"] = v.VerifierOrgID
	v.fieldMap["verifier_org_name"] = v.VerifierOrgName
	v.fieldMap["verification_type"] = v.VerificationType
	v.fieldMap["purpose"] = v.Purpose
	v.fieldMap["input_type"] = v.InputType
	v.fieldMap["input_data"] = v.InputData
	v.fieldMap["result"] = v.Result
	v.fieldMap["result_details"] = v.ResultDetails
	v.fieldMap["matched_fields"] = v.MatchedFields
	v.fieldMap["mismatch_fields"] = v.MismatchFields
	v.fieldMap["blockchain_verified"] = v.BlockchainVerified
	v.fieldMap["blockchain_result"] = v.BlockchainResult
	v.fieldMap["report_url"] = v.ReportURL
	v.fieldMap["report_id"] = v.ReportID
	v.fieldMap["risk_level"] = v.RiskLevel
	v.fieldMap["risk_factors"] = v.RiskFactors
	v.fieldMap["reviewed_by"] = v.ReviewedBy
	v.fieldMap["reviewed_at"] = v.ReviewedAt
	v.fieldMap["review_result"] = v.ReviewResult
	v.fieldMap["review_notes"] = v.ReviewNotes
	v.fieldMap["ip_address"] = v.IPAddress
	v.fieldMap["user_agent"] = v.UserAgent
	v.fieldMap["location"] = v.Location
	v.fieldMap["status"] = v.Status
	v.fieldMap["expires_at"] = v.ExpiresAt
	v.fieldMap["verified_at"] = v.VerifiedAt
	v.fieldMap["created_at"] = v.CreatedAt
	v.fieldMap["updated_at"] = v.UpdatedAt
}

func (v verification) clone(db *gorm.DB) verification {
	v.verificationDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v verification) replaceDB(db *gorm.DB) verification {
	v.verificationDo.ReplaceDB(db)
	return v
}

type verificationDo struct{ gen.DO }

type IVerificationDo interface {
	gen.SubQuery
	Debug() IVerificationDo
	WithContext(ctx context.Context) IVerificationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVerificationDo
	WriteDB() IVerificationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVerificationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVerificationDo
	Not(conds ...gen.Condition) IVerificationDo
	Or(conds ...gen.Condition) IVerificationDo
	Select(conds ...field.Expr) IVerificationDo
	Where(conds ...gen.Condition) IVerificationDo
	Order(conds ...field.Expr) IVerificationDo
	Distinct(cols ...field.Expr) IVerificationDo
	Omit(cols ...field.Expr) IVerificationDo
	Join(table schema.Tabler, on ...field.Expr) IVerificationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVerificationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVerificationDo
	Group(cols ...field.Expr) IVerificationDo
	Having(conds ...gen.Condition) IVerificationDo
	Limit(limit int) IVerificationDo
	Offset(offset int) IVerificationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVerificationDo
	Unscoped() IVerificationDo
	Create(values ...*model.Verification) error
	CreateInBatches(values []*model.Verification, batchSize int) error
	Save(values ...*model.Verification) error
	First() (*model.Verification, error)
	Take() (*model.Verification, error)
	Last() (*model.Verification, error)
	Find() ([]*model.Verification, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Verification, err error)
	FindInBatches(result *[]*model.Verification, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Verification) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVerificationDo
	Assign(attrs ...field.AssignExpr) IVerificationDo
	Joins(fields ...field.RelationField) IVerificationDo
	Preload(fields ...field.RelationField) IVerificationDo
	FirstOrInit() (*model.Verification, error)
	FirstOrCreate() (*model.Verification, error)
	FindByPage(offset int, limit int) (result []*model.Verification, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVerificationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v verificationDo) Debug() IVerificationDo {
	return v.withDO(v.DO.Debug())
}

func (v verificationDo) WithContext(ctx context.Context) IVerificationDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v verificationDo) ReadDB() IVerificationDo {
	return v.Clauses(dbresolver.Read)
}

func (v verificationDo) WriteDB() IVerificationDo {
	return v.Clauses(dbresolver.Write)
}

func (v verificationDo) Session(config *gorm.Session) IVerificationDo {
	return v.withDO(v.DO.Session(config))
}

func (v verificationDo) Clauses(conds ...clause.Expression) IVerificationDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v verificationDo) Returning(value interface{}, columns ...string) IVerificationDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v verificationDo) Not(conds ...gen.Condition) IVerificationDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v verificationDo) Or(conds ...gen.Condition) IVerificationDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v verificationDo) Select(conds ...field.Expr) IVerificationDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v verificationDo) Where(conds ...gen.Condition) IVerificationDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v verificationDo) Order(conds ...field.Expr) IVerificationDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v verificationDo) Distinct(cols ...field.Expr) IVerificationDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v verificationDo) Omit(cols ...field.Expr) IVerificationDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v verificationDo) Join(table schema.Tabler, on ...field.Expr) IVerificationDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v verificationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVerificationDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v verificationDo) RightJoin(table schema.Tabler, on ...field.Expr) IVerificationDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v verificationDo) Group(cols ...field.Expr) IVerificationDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v verificationDo) Having(conds ...gen.Condition) IVerificationDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v verificationDo) Limit(limit int) IVerificationDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v verificationDo) Offset(offset int) IVerificationDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v verificationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVerificationDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v verificationDo) Unscoped() IVerificationDo {
	return v.withDO(v.DO.Unscoped())
}

func (v verificationDo) Create(values ...*model.Verification) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v verificationDo) CreateInBatches(values []*model.Verification, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v verificationDo) Save(values ...*model.Verification) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v verificationDo) First() (*model.Verification, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Verification), nil
	}
}

func (v verificationDo) Take() (*model.Verification, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Verification), nil
	}
}

func (v verificationDo) Last() (*model.Verification, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Verification), nil
	}
}

func (v verificationDo) Find() ([]*model.Verification, error) {
	result, err := v.DO.Find()
	return result.([]*model.Verification), err
}

func (v verificationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Verification, err error) {
	buf := make([]*model.Verification, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v verificationDo) FindInBatches(result *[]*model.Verification, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v verificationDo) Attrs(attrs ...field.AssignExpr) IVerificationDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v verificationDo) Assign(attrs ...field.AssignExpr) IVerificationDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v verificationDo) Joins(fields ...field.RelationField) IVerificationDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v verificationDo) Preload(fields ...field.RelationField) IVerificationDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v verificationDo) FirstOrInit() (*model.Verification, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Verification), nil
	}
}

func (v verificationDo) FirstOrCreate() (*model.Verification, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Verification), nil
	}
}

func (v verificationDo) FindByPage(offset int, limit int) (result []*model.Verification, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v verificationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v verificationDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v verificationDo) Delete(models ...*model.Verification) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *verificationDo) withDO(do gen.Dao) *verificationDo {
	v.DO = *do.(*gen.DO)
	return v
}
